### ISSUE TITLE
Question: Anyway to get bbot not to take screenshots of postman and github?

### ISSUE THREAD

**Issue by specters312** [blacklanternsecurity/bbot#1026]
**Description**
BBOT takes many screenshots of postman and github and I don't want them but want that data somewhere else

**Comment by TheTechromancer** [comment]
Thanks for catching this! It's definitely a bug; I will work on a fix.

**Comment by TheTechromancer** [comment]
This has been fixed in https://github.com/blacklanternsecurity/bbot/pull/1027.

**Comment by specters312** [comment]
Holy shit you are awesome thanks <3
I realized the gowitness could've been in the wrong module so I was thinking it should be under its own like "screenshot/evidence" etc. but was to nervous to make a suggestion.
