### ISSUE TITLE
Wildcard evading detection

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#1031]
![image](https://github.com/blacklanternsecurity/bbot/assets/24899338/1196bc5f-53e3-4007-89fb-2d9b2741003e)

Observed on *.cloudflare.jitsi.net

Appears to only return CNAME records

**Comment by TheTechromancer** [comment]
Can you post your command including any config changes? I ran `-f subdomain-enum` and it correctly identified the wildcard:

![image](https://github.com/blacklanternsecurity/bbot/assets/20261699/4859c82d-c12e-4235-b659-f88c5ce5ac75)

**Comment by TheTechromancer** [comment]
Ah nevermind, I see what's happening

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1033.
