### ISSUE TITLE
Error when running Budget mode for Nuclei

### ISSUE THREAD

**Issue by a7t0fwa7** [blacklanternsecurity/bbot#1054]
**Describe the bug**
Running the Budget nuclei mode does not seem to work I get an error thrown as shown in the screenshot below

bbot -f subdomain-enum web-basic -m nmap nuclei -–allow-deadly –c modules.nuclei.mode=Budget -t app1.evilcorp.com app2.evilcorp.com app3.evilcorp.com​

![image](https://github.com/blacklanternsecurity/bbot/assets/43460290/dba0a378-84f1-46d0-a65b-2ef19610be8c)

**Comment by liquidsec** [comment]
I think you might have just copied some bad characters for your hyphens on --allow-deadly and -c, also budget should have a lowercase b. If you copied the command from our documentation, can you let us know where? If so we will clean up the junk characters. I'll go ahead and close, but if you have any other issues let us know!

**Comment by liquidsec** [comment]
Hey, just wanted to let you know we did find some weird characters in our docs which was probably what you copied. We also will be making the mode case insensitive. 

https://github.com/blacklanternsecurity/bbot/pull/1077

**Comment by a7t0fwa7** [comment]
Thanks man appreciated. Love your work guys
