### ISSUE TITLE
Improve Recursive Module Dependency System

### ISSUE THREAD

**Issue by stryker2k2** [blacklanternsecurity/bbot#1060]
### Description:
- While creating the `newsletters` module, I discovered that my module required ["URL"] and could utilize either `httpx` or `gowitness` to provide ["URL"] to watch. But, since there were two dependent modules to chose from, BBOT decided to chose neither and require the Operator to pick one.

### Disclaimer:
- This is not a bug report. This improvement is already planned. Refer to `cli.py:162`. This ticket will serve as the BBOT Project Ticket for this planned improvement.

### Expected Input:
`bbot -m newsletters`

### Actual Input:
`bbot -m httpx newsletters`

### Ideas:
- [ ] Automagically have BBOT decide which module is best and use that one
OR
- [ ] Create a `recursive_deps` variable that the module developer populates when creating a module (ex: recursive_deps = ['httpx', 'example1', 'example2']) that `cli.py:163` then parses and recursively includes that module at runtime.

![Image](https://github.com/blacklanternsecurity/bbot/assets/18358246/43860428-28a4-44e0-898a-1df320c47965)

**Comment by TheTechromancer** [comment]
This has been implemented in https://github.com/blacklanternsecurity/bbot/pull/1058.
