### ISSUE TITLE
Some Errors in BBOT: Telerik and Postman

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1062]
I found these errors during my testings in bbot, unfortunately cant remember if it was dev version or stable one. (But i can find out if you needed)

![Termius_2024-02-05_20-46-00](https://github.com/blacklanternsecurity/bbot/assets/15929497/c15ca0e2-92ba-46cd-83c2-f2ac91641ebd)
![Termius_2024-02-05_18-37-30](https://github.com/blacklanternsecurity/bbot/assets/15929497/4746c0d6-57cd-4466-8355-8827d7081938)

**Comment by TheTechromancer** [comment]
@amiremami do you still have `debug.log` for `despicable_jayce`?

**Comment by Sh4d0wHunt3rX** [comment]
Unfortunately, I terminated all servers few hours ago 🤦‍♂️

**Comment by TheTechromancer** [comment]
Telerik bug fixed in https://github.com/blacklanternsecurity/bbot/pull/1066, postman in https://github.com/blacklanternsecurity/bbot/pull/1067.
