### ISSUE TITLE
Detect WAF Blocks

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1068]
Similar to what we currently have for `cloudcheck`, we should implement a system that detects when a WAF blocks us and tags `URL`s and `HTTP_RESPONSE`s accordingly.

I first noticed this when scanning `tesla.com`. Akamai IP blocked me and caused `bypass403` to generate hundreds of false positives.

Right now there is a single WAF signature hardcoded in `bypass403`. Ideally we should make a similar system to `cloudcheck` that detects WAF blocks and tags them. Then, in `bypass403.filter_event()`, we could reject these WAF blocks.

It wouldn't be too dificult to use wafw00f's signatures. Their modules look like this:

```python
#!/usr/bin/env python
'''
Copyright (C) 2022, WAFW00F Developers.
See the LICENSE file for copying permission.
'''

NAME = 'Safe3 Web Firewall (Safe3)'


def is_waf(self):
    if self.matchHeader(('Server', 'Safe3 Web Firewall')):
        return True

    if self.matchHeader(('X-Powered-By', r'Safe3WAF/[\.0-9]+?')):
        return True

    if self.matchContent(r'Safe3waf/[0-9\.]+?'):
        return True

    return False
```

**Comment by liquidsec** [comment]
will possibly revisit someday, but not relevant currently
