### ISSUE TITLE
Wafw00f should not follow redirects

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1083]
We should change wafw00f behavior to make sure it doesn't follow redirects. Thanks to @amiremami for discovering.

![image](https://github.com/blacklanternsecurity/bbot/assets/20261699/cc5af925-6992-4bc7-99b5-f7002c078f9e)

**Comment by liquidsec** [comment]
There's a trade off here either way, following them will solve some false positives/false negatives and add others.

**Comment by TheTechromancer** [comment]
There shouldn't be any tradeoff since BBOT follows redirects itself, right? The destination URL will end up coming back to wafw00f.

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1002.
