### ISSUE TITLE
Socks5 Proxy Not Works

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1092]
I tried the socks5 proxy on dev version of bbot but couldn't make it work.

bbot -f subdomain-enum -t tesla.com -om asset_inventory -o /root/.bbot/scans/test/ -n "$(date +'%Y_%m_%d_%H%M%S')" -c omit_event_types=[] --config http_proxy=socks5://USERNAME:PASSWORD@geo.iproyal.com:32325

![1](https://github.com/blacklanternsecurity/bbot/assets/15929497/4d515b89-c47b-4721-aa27-e4747a4e9871)

I tried to remove h, but didn't work either:

![2](https://github.com/blacklanternsecurity/bbot/assets/15929497/24b21684-9241-4c1d-8180-7109b845f410)

Thanks 🙏

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1094.

**Comment by Sh4d0wHunt3rX** [comment]
@TheTechromancer , I got these on bbot v1.1.6.2879rc today with proxy

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/50abe737-5955-4b0d-a37a-8e05b6a54e02)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/73331dde-cf04-4ae8-8916-79e07cfd7299)

**Comment by TheTechromancer** [comment]
Thanks for testing this. Can you post the traceback from debug.log?

**Comment by Sh4d0wHunt3rX** [comment]
[debug.txt](https://github.com/blacklanternsecurity/bbot/files/14311494/debug.txt)

You're welcome : ) Does this help?
