### ISSUE TITLE
Make HTTP Endpoint SIEM friendly

### ISSUE THREAD

**Issue by nicpenning** [blacklanternsecurity/bbot#1097]
**Description**
Since the SIEM-friendly feature was recently added to standardize JSON for ingest on the JSON output, it would be great to extend this logic to http endpoint so that that information can also be pushed in this same format.

Reference to the JSON output feature:
https://github.com/blacklanternsecurity/bbot/discussions/736#discussioncomment-8492531

The use case will allow engineers to have the data be pushed into SIEMs with the appropriate JSON objects and it will help with consistency of the data.

**Comment by TheTechromancer** [comment]
Added in https://github.com/blacklanternsecurity/bbot/pull/1101.
