### ISSUE TITLE
Logging Error

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1134]
I see this logging error in almost all of my scans when crawling. Not sure if it's harmless or not, just wanted to report. No any trace of error in debug.log

![Termius_2024-02-27_09-01-02](https://github.com/blacklanternsecurity/bbot/assets/15929497/ff97a076-c943-4112-9f47-d4dea9b40ff6)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/5357968e-d2b3-4090-a656-86beddd33061)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/14268964-af51-4e2a-9b3d-f4254c0c3a43)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/752f2507-0f8d-4fd4-a6be-2ab6e05d9141)

**Comment by TheTechromancer** [comment]
Thanks for reporting. A fix was already merged for this (https://github.com/blacklanternsecurity/bbot/pull/1051). Are you running the latest dev?

**Comment by Sh4d0wHunt3rX** [comment]
> Thanks for reporting. A fix was already merged for this (#1051). Are you running the latest dev?

You're welcome : )

First image was with BBOT v1.1.6.2879rc , not sure about the second one, but for openai (the last two) : BBOT v1.1.7.2984rc

**Comment by TheTechromancer** [comment]
Upstream issue: https://github.com/vxgmichel/aioconsole/issues/99

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1136.
