### ISSUE TITLE
Full Scan Warnings & Errors

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1137]
I ran a full scan with all flags enabled + APIs. I report here all warnings and errors I got.

1. I know, this warning will be changed in future, but why it says I have one dns server? Did I set something wrong?

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/d5de93de-91c4-406c-a400-535362eacd8e)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/c58b53c7-137a-43e2-a43e-bbc5ce083f1d)

2. Newsletters

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/000fdba0-9d60-4fe3-b20c-f941d7dda89a)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/cb1d5478-1635-4f90-a646-f350aabe0cf5)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/ee88dd3e-e46c-4067-b540-1d5d9cb7a294)

3. Gowintness

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/776d4428-708b-4178-8cdc-080cc9f020a8)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/1aacce09-f066-40f9-8775-78aca441e9ec)

4. Interact.sh (got this hundreds of times)

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/78c72f41-c06a-4090-84b7-ef9b82175ece)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/95566b07-8516-4003-b8f4-5669ee03e111)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/93a46d4b-30a1-456a-b7c6-5116973c3696)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/6c2d708e-6d55-48c9-a156-26f30a9d347a)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/1152ce92-a51e-43c4-8b7f-afabf7cf1907)

5. ASN (got this several times)

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/4801dd57-10f5-4281-bfe0-51817cbf3832)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/335d0d15-372e-487c-9385-97e2f9dcc79a)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/92bfcd57-90fb-4048-b96d-77a3bec68aac)

For the last two errors, I also got them before, reported in #1053 , in my initial investigation it was coming from Telerik, but can't be sure, because if we enable --debug then there won't be any error anymore. At least this is what I experienced last month. I can try another time with enabling debug if needed. But this time, scan didn't crash and successfully finished.

6. How to disable screenshots of social media pages?

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/398b10ba-e34f-4ba7-963d-b53ba0e564c0)

7. Some errors from debug.log

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/e7a28871-64e6-4b4c-8bfb-639ad9dc9e62)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/c76c218e-b133-4f9a-8b95-1702e9ed3b0c)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/df35560d-6de1-49f0-afc0-22b496a37ba4)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/88a93451-caaf-4064-8cd9-1d15a222649c)

**Comment by TheTechromancer** [comment]
Jesus @amiremami you're on a roll today

**Comment by TheTechromancer** [comment]
I will add an option to gowitness to disable social media. In the meantime, would you mind running that same scan again with `-c http_debug=true?` You don't need to enable `--debug`. Hopefully that will be enough to catch the interactsh error.

**Comment by Sh4d0wHunt3rX** [comment]
> I will add an option to gowitness to disable social media. In the meantime, would you mind running that same scan again with `-c http_debug=true?` You don't need to enable `--debug`. Hopefully that will be enough to catch the interactsh error.

By mistake I wrote my command like this:

-c web_spider_distance=4 web_spider_depth=4 web_spider_links_per_page=500 omit_event_types=[] url_extension_httpx_only=[] -c http_debug=true?

[-c twice, not sure if it worked or not, but error showed up]

[debug.log](https://github.com/blacklanternsecurity/bbot/files/14437941/debug.log)

**Comment by Sh4d0wHunt3rX** [comment]
It seems, FILEDOWNLOAD also downloads from github, that would be great if we can download only from scope.

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/3df6fcda-94ae-4185-98fd-b5a3fbfcaf01)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/d046c398-f81e-4a26-9b36-ae4244b64506)

**Comment by Sh4d0wHunt3rX** [comment]
How to prevent gowitness to screenshot the images?

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/73069bf9-3422-480d-b5cf-0be9331d8857)

**Comment by TheTechromancer** [comment]
> How to prevent gowitness to screenshot the images?

.webp wasn't in the extension blacklist. Fixed in https://github.com/blacklanternsecurity/bbot/pull/1140.

**Comment by TheTechromancer** [comment]
Closing as we have separate issues for these.
