### ISSUE TITLE
Filedownload should only download in-scope items

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1141]
As mentioned in https://github.com/blacklanternsecurity/bbot/issues/1137:

![image](https://github.com/blacklanternsecurity/bbot/assets/20261699/2a0cbb1d-00a6-4261-b93e-74a24fe3911d)

**Comment by nicpenning** [comment]
Confirmed, a scan with strict-scope and whitelist, does not prevent files being download from externally referenced websites:

Example: `bbot -t {target} -f safe --strict-scope --whitelist {target}`

This happens on version 1.1.8 (using docker).

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1428.

Also FYI @nicpenning, you don't need to specify both `--target` and `--whitelist` if they're the same.

**Comment by nicpenning** [comment]
Perfect, thank you! I was trying both just in case haha!
