### ISSUE TITLE
while parsing a block mapping

### ISSUE THREAD

**Issue by meetgyn** [blacklanternsecurity/bbot#1157]
I've tried several ways, but Bbot doesn't work. I did installation via pip because docker was with errors.
What should I do?
I'm using Kali Linux with kernel 5.10.0-kali9-amd64

![image](https://github.com/blacklanternsecurity/bbot/assets/3695608/90d253ec-797b-4a3c-954e-802b8bc07f6d)
![image](https://github.com/blacklanternsecurity/bbot/assets/3695608/53706e92-f993-41f4-b41e-b1c151c2a3c2)

**Comment by TheTechromancer** [comment]
Your config file is not valid YAML. It needs to match the format as in the docs:

https://www.blacklanternsecurity.com/bbot/#api-keys

**Comment by TheTechromancer** [comment]
Closing as resolved, feel free to reopen if you're still running into issues.
