### ISSUE TITLE
Module Todo: Subdomain Hijacking

### ISSUE THREAD

**Issue by aconite33** [blacklanternsecurity/bbot#116]
Create a module that will support the identification of vulnerable subdomains that could be victim of a take over

https://medium.com/@nynan/what-i-learnt-from-reading-217-subdomain-takeover-bug-reports-c0b94eda4366

Examples Projects:

* https://github.com/gfek/Lepus/blob/master/submodules/TakeOver.py
* https://github.com/EdOverflow/can-i-take-over-xyz
* https://github.com/haccer/subjack
* https://github.com/shmilylty/OneForAll/blob/master/data/fingerprints.json
* https://github.com/Ice3man543/SubOver
* https://0xpatrik.com/subdomain-takeover-basics

**Comment by TheTechromancer** [comment]
Messaged @EdOverflow on Twitter to see if he's open to collaborating on his can-i-take-over-xyz repo, which seems to be the best repository for subdomain hijacking data. @liquidsec

**Comment by liquidsec** [comment]
putting on hold until a suitable long-term solution is nailed down for maintaining

**Comment by TheTechromancer** [comment]
![image](https://user-images.githubusercontent.com/20261699/206031748-5a65f503-162b-4102-9d45-35869e4f01c9.png)

**Comment by TheTechromancer** [comment]
Pull request opened: https://github.com/EdOverflow/can-i-take-over-xyz/pull/336

**Comment by TheTechromancer** [comment]
TIL that nuclei is where all the subdomain hijacking stuff is happening these days
https://github.com/projectdiscovery/nuclei-templates/tree/master/takeovers

@liquidsec

**Comment by TheTechromancer** [comment]
Added in https://github.com/blacklanternsecurity/bbot/pull/212
