### ISSUE TITLE
Blocked scan: "api count exceeded - increase quota with membership"

### ISSUE THREAD

**Issue by cosad3s** [blacklanternsecurity/bbot#1161]
**Describe the bug**

After some scan, bbot cannot be launched anymore because of following error:

```bash
[ERRR] Unable to autodetect event type from "api count exceeded - increase quota with membershipX.X.X.X.target.com" (--debug for details)
```

*(Its very similar to https://github.com/blacklanternsecurity/bbot/issues/483)*

**Expected behavior**

Bypass this check without interrupting the scan if bbot fails on this check.

**BBOT Command**

`bbot -f active,safe -m nuclei --allow-deadly -c modules.nuclei.templates=/mytemplates/ -om discord -c output_modules.discord.webhook_url=https://discord.com/api/webhooks/1234/WEBHOOK -ef baddns,host_header,hackertarget -t targets.txt --debug`

*(as you can see, I tried to exclude `hackertarget` module, refered to https://github.com/blacklanternsecurity/bbot/issues/483 - without success)*

**OS, BBOT Installation Method + Version**

```bash
❯ bbot --version
v1.1.6
```

On Kali Linux

**BBOT Config**

No configuration file.

**Logs**

Extract (redacted):

```bash
[DBUG] Autodetected event type "DNS_NAME" based on data: "a.target.com"
[DBUG] Autodetected event type "DNS_NAME" based on data: "b.target.com"
[DBUG] Autodetected event type "DNS_NAME" based on data: "c.target.com"
[ERRR] Unable to autodetect event type from "api count exceeded - increase quota with membershipX.X.X.X.target.com" (--debug for details)
[DBUG] Traceback (most recent call last):
  File "/x/python3.11/site-packages/bbot/cli.py", line 137, in _main
    scanner = Scanner(
              ^^^^^^^^
  File "/x/python3.11/site-packages/bbot/scanner/scanner.py", line 203, in __init__
    self.target = Target(self, *targets, strict_scope=strict_scope, make_in_scope=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/x/python3.11/site-packages/bbot/scanner/target.py", line 95, in __init__
    self.add_target(t)
  File "/x/python3.11/site-packages/bbot/scanner/target.py", line 127, in add_target
    event = self.scan.make_event(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/x/python3.11/site-packages/bbot/scanner/scanner.py", line 778, in make_event
    event = make_event(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/x/python3.11/site-packages/bbot/core/event/base.py", line 1276, in make_event
    event_type, data = get_event_type(data)
                       ^^^^^^^^^^^^^^^^^^^^
  File "/x/python3.11/site-packages/bbot/core/event/helpers.py", line 52, in get_event_type
    raise ValidationError(f'Unable to autodetect event type from "{data}"')
bbot.core.errors.ValidationError: Unable to autodetect event type from "api count exceeded - increase quota with membershipX.X.X.X.target.com"
```

**Screenshots**

N/A

**Comment by TheTechromancer** [comment]
`-ef` is for excluding flags. To exclude a module, you need to use `-em`.

Can you post the contents of `targets.txt`?

**Comment by cosad3s** [comment]
Thanks @TheTechromancer for the option, yes a mistake. Also I have seen that the Web documentation is not coherent with the documentation in this repository regarding the modules activated by flag :

- https://www.blacklanternsecurity.com/bbot/scanning/#modules-m
- https://github.com/blacklanternsecurity/bbot/blob/stable/docs/scanning/index.md
*(for instance, the module `baddns` does not exists anymore)*

Then, I have solved my problem to finish ... There were a "funny" problem in my `targets.txt` file: one of the line was `api count exceeded - increase quota with membershipX.X.X.X.target.fr` 🥲 I was confused because of that

**Comment by TheTechromancer** [comment]
Ah yes, I can see the wording is confusing. That can be fixed. As for baddns, it's a brand-new module which is currently in the bleeding-edge version of bbot. Stay tuned for a blog post on that ;)

The lists of modules, flags, etc. in the documentation are auto-generated from what's in the `dev` branch.
