### ISSUE TITLE
Cloud Helper Module: Tagging Cloud Resources

### ISSUE THREAD

**Issue by aconite33** [blacklanternsecurity/bbot#117]
Add functionality to the Cloud Helper function to tag appropriate returned events as "Cloud" resources when discovered (e.g., AWS/Azure/Google Cloud/CloudFlare IPs, DNS, Websites, Endpoints)

**Comment by TheTechromancer** [comment]
Added in https://github.com/blacklanternsecurity/bbot/pull/164
