### ISSUE TITLE
Killing Module Not Works

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1174]
I'm using bbot v1.1.7.3042rc, I'm not sure if there is a bug or I'm not doing it correctly, but when I kill a module, the module continues working, maybe I need to wait to finish processing events? 

For example, here nuclei, won't stop and continues working.

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/b6706017-915c-4736-bdf2-4b1d54864a9e)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/78d00e01-b85f-412e-8371-14740a0f994a)

I expect when I kill a module, I don't see it afterwards in the terminal.

**Comment by TheTechromancer** [comment]
@amiremami thanks for discovering this. It looks like killing a module doesn't kill its subprocesses. This means that when a module like nuclei (that executes a subprocess in the background) is killed, it won't die fully until after the current process exits.

This is a bug but should be pretty easily fixable.

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1185.

**Comment by Sh4d0wHunt3rX** [comment]
Hey @TheTechromancer , it seems this issue exists for Vhost module on v1.1.7.3235rc, can you check? 🙏

**Comment by TheTechromancer** [comment]
Typing `kill vhost` seems to be working for me. However, I have noticed some weirdness with the keyboard interaction lately, especially with big scans: https://github.com/blacklanternsecurity/bbot/issues/1276

![image](https://github.com/blacklanternsecurity/bbot/assets/20261699/d7504e6c-1601-4291-ac79-0d35d085feab)

**Comment by Sh4d0wHunt3rX** [comment]
Yes exactly, at first, it works fine, but then in the middle of big scan, it won't work correctly. I guess it's exactly what you noticed.

**Comment by Sh4d0wHunt3rX** [comment]
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/c6c780fd-5e86-4bd9-8133-dd432a9d46e1)
