### ISSUE TITLE
Emit TECHNOLOGY Events from Nuclei Module

### ISSUE THREAD

**Issue by SpamFaux** [blacklanternsecurity/bbot#1178]
**Description**
Which feature would you like to see added to BBOT? What are its use cases?

The existing Nuclei module can run technology identification templates (i.e. Exposed Panels) to identify the applications running on an asset. This will enhance the quality of the TECHNOLOGY events for data classification and building a better picture of scanned Attack Surfaces.

**Comment by TheTechromancer** [comment]
Added in https://github.com/blacklanternsecurity/bbot/pull/1179.
