### ISSUE TITLE
Human Output shows even when --silent (-s) is selected

### ISSUE THREAD

**Issue by stryker2k2** [blacklanternsecurity/bbot#1180]
## **Describe the bug**
Human Output displayed when --silent was selected

## **Expected behavior**
Expected no STDOUT/STDERR output (or just a single line with `scan_name`)

## **BBOT Command**
``` Python
$ bbot -m httpx newsletters -t blacklanternsecurity --silent
[SCAN]              	wet_theresa (SCAN:fa2681321580b2d7ef7a251354a944acb553f017)	TARGET	(in-scope)
[DNS_NAME]          	blacklanternsecurity	TARGET	(a-error, aaaa-error, in-scope, target, unresolved)
```

## **OS, BBOT Installation Method + Version**
BBOT Dev Branch (Commit [0385303](https://github.com/blacklanternsecurity/bbot/commit/038530332f920b9f331456a6ad2b4c5b107da45d))

**Comment by TheTechromancer** [comment]
This is intended. The `--silent` option is meant to silence stderr, not stdout. If you don't want the stdout, you can choose a different output module other than `human`.

We could probably update the `--help` to be more clear about this.
