### ISSUE TITLE
Module: Service Enumeration (Nmap etc)

### ISSUE THREAD

**Issue by aconite33** [blacklanternsecurity/bbot#119]
Add a module that will allow for the enumeration of TCP ports and identification of services running on enumerated port.

Example Projects:

* [Nmap](https://github.com/nmap/nmap)
* https://www.praetorian.com/blog/fingerprintx/
* https://github.com/projectdiscovery/naabu

**Comment by TheTechromancer** [comment]
+1 for fingerprintx

**Comment by TheTechromancer** [comment]
Added in https://github.com/blacklanternsecurity/bbot/pull/253
