### ISSUE TITLE
Graduate Agent to Standalone Tool

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1195]
With the completion of presets and the 2.0 release approaching, now is the best time for the agent to graduate to its own tool.

Considering its importance and how much it's used by @SpamFaux and ASMOC, it deserves its own project. In core, it feels a bit like a second-class citizen.

Recalling our plan from BBOT CON, the ultimate goal is to make the agent and asset inventory standalone tools that are dependent on I/O modules. So it makes sense to separate them before they get too intertwined with core.

TODO:
- [x] Remove agent functionality from core (preset branch)
- [x] Meet with Sam, Jason, and Kerry to get an idea of what they need from the agent
    - [x] Ideas for improvements / changes
        - [ ] Logging functionality
            - [ ] Realtime log streaming (log handler)
            - [ ] One-time log retrieval (entire file)
            - [ ] Ability to toggle log level during in-progress scan (similar to CLI)
        - [ ] Ability to pull current agent config (equivalent of `--current-config`)
        - [ ] Full support for presets
- [x] Create new private Github repo for agent
    - [x] Create README
    - [x] Recreate CLI functionality (see [`bbot/agent`](https://github.com/blacklanternsecurity/bbot/tree/dev/bbot/agent) folder in `dev`)
    - [x] Recreate tests (see [`bbot/test/test_step_1/test_agent.py`](https://github.com/blacklanternsecurity/bbot/blob/dev/bbot/test/test_step_1/test_agent.py) in `dev`)
        - [x] Set up Github Actions (see [`.github/workflows/tests.yml`](https://github.com/blacklanternsecurity/bbot/blob/dev/.github/workflows/tests.yml) in `dev`)

NOTE: Since agent functionality has been removed from presets, this needs to be completed before the 2.0 release.

**Comment by stryker2k2** [comment]
Roger that. Working on it now.

**Comment by stryker2k2** [comment]
Private Repo can be found https://github.com/blacklanternsecurity/bbotagent/ in which there are two branches, a blank `stable` branch and a `dev` branch.

Minimal Viable Product functionality has been restored and currently interacts with the `presets` branch of BBOT Core. The `test_agent` does properly spin up a websocket hosts and communicates with BBOT Core. A `cli.py` file does exist but does not accept any command line args yet.

**Comment by stryker2k2** [comment]
- README has been updated (dev branch) with an Installation & Usage Guide.
- Agent has minimal CLI Functionality... it should be able to handle anything the BBOT-GUI throws at it without any CLI Args
  - The "wshost.py" does have CLI Functionality (need improvement) where the CLI User can pass in arguments to test the Agent
