### ISSUE TITLE
Nuclei mode not changing to severe when using BBOT as a python library

### ISSUE THREAD

**Issue by jerinjose61** [blacklanternsecurity/bbot#1200]
**Describe the bug**
I am using BBOT as a python library and is trying to change the nuclei mode to 'severe' from the default of 'manual'. I tried the following ways:

`scan = Scanner(
        *targets, modules=modules, strict_scope=True,
        config={
            "modules.massdns.max_resolvers": 5000,
            "modules.nuclei.mode": 'severe'
        }
    )
`

AND

`scan = Scanner(
        *targets, modules=modules, strict_scope=True,
        config={
            "modules.massdns.max_resolvers": 5000,
            "modules.deadly.nuclei.mode": 'severe'
        }
    )
`

However, when running the scan, it still shows that the scan is running in 'manual' mode.

**Expected behavior**
The scan should run on 'severe' mode rather than 'manual' mode.

**OS, BBOT Installation Method + Version**
`OS: Ubuntu Server 22.04 LTS running on a Raspberry Pi, Installation method: pip, BBOT version: v1.1.6`

**Logs**
[WARN] BBOT performs better with multiple DNS servers. Your system currently only has one.
[INFO] Scan with 8 modules seeded with 3 targets
[INFO] Loaded 8/8 scan modules (ajaxpro,badsecrets,dastardly,generic_ssrf,httpx,internetdb,nuclei,telerik)
[INFO] Loaded 3/3 internal modules (aggregate,excavate,speculate)
[INFO] Loaded 1/1 output modules, (python)
[INFO] Setting up modules...
[INFO] Registering with interact.sh server: oast.online
[INFO] nuclei: Updating Nuclei templates
[INFO] internal.speculate: No portscanner enabled. Assuming open ports: 80, 443
[INFO] Successfully registered to interactsh server oast.online with correlation_id 63fl125hbf67481s8859 [63fl125hbf67481s8859lv181n7ihu42q.oast.online]
[INFO] nuclei: Nuclei templates already up-to-date
**[INFO] nuclei: Running nuclei in MANUAL mode. Settings will be passed directly into nuclei with no modification**
[SUCC] Setup succeeded for 12/12 modules.

**Comment by TheTechromancer** [comment]
The config needs to be formatted like this:

```json
{
  "modules": {
    "massdns": {
      "max_resolvers": 5000
    },
    "nuclei": {
      "mode": "severe"
    }
  }
}
```

**Comment by jerinjose61** [comment]
Awesome! Thanks a ton for the response @TheTechromancer
