### ISSUE TITLE
Module: Default Credential Scanning

### ISSUE THREAD

**Issue by aconite33** [blacklanternsecurity/bbot#121]
Add a module that will search for default credentials within an environment. Should operate after TCP ports have been enumerated.

Examples Projects:

* https://github.com/projectdiscovery/nuclei
* https://github.com/lanjelot/patator
* https://github.com/nmap/nmap

**Comment by liquidsec** [comment]
This is pretty well covered by nuclei's default-login templates. Is there something beyond what nuclei can provide that you had in mind?

**Comment by aconite33** [comment]
The goal is to replicate what we do with https://github.com/blacklanternsecurity/zmap-asset-inventory in order to achieve similar coverage.

SSH
Telnet
FTP / Anonymous FTP
NFS
iSCSI

All Non HTTP/HTTPS protocols
