### ISSUE TITLE
Default Mode Nuclei in Documentation

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1216]
In documentation, I noticed paradox for nuclei default mode

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/78a8501b-d0be-463e-a589-179d60281221)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/28099041-ea14-43a3-9d9a-8bb4490297d4)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/3ce311c8-8e85-48e1-96d1-4fb22aef4e35)

**Comment by TheTechromancer** [comment]
It turns out we have this set correctly, it is a markdown parsing error because the description for that option has `|` characters in it:

![image](https://github.com/blacklanternsecurity/bbot/assets/20261699/4adc8a7f-0f3c-4312-b437-e75f73ccb05c)

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1217.
