### ISSUE TITLE
Paramminer warning

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1222]
I noticed this warning from paramminer. No extra info in debug.log

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/df23a323-f91c-4e21-9c2a-d139d07bde35)

**Comment by liquidsec** [comment]
Seeing this message should be rare, but is still within the realm of possible "normal" behavior. Therefore, I am changing it from a warning to a debug, and adding some more details into the debug message.

https://github.com/blacklanternsecurity/bbot/pull/1259
