### ISSUE TITLE
`tool.poetry-dynamic-versioning.enable` is set to `true` in v1.1.6.1

### ISSUE THREAD

**Issue by mtkennerly** [blacklanternsecurity/bbot#1257]
**Describe the bug**
Hi! I got an inquiry (https://github.com/mtkennerly/dunamai/issues/80) about a build failure in Homebrew for v1.1.6.1. I noticed that `tool.poetry-dynamic-versioning.enable` is set to `true`, so it's trying to reference the Git history, which isn't available in the `.tar.gz` artifact. I suspect that someone may have run `poetry build && poetry publish` without `poetry-dynamic-versioning` installed, so the plugin couldn't update that field to `false` while building the artifacts.

**Expected behavior**
The field should be set to `false` in the published artifacts.

**Comment by TheTechromancer** [comment]
Thanks for reporting. I do have `poetry-dynamic-version` installed, so I'm not sure why it's not being disabled during publish. I've manually set `enable = false` and pushed a new version, `1.1.6.3`.  @chenrui333 can you try it again?

**Comment by mtkennerly** [comment]
> I do have `poetry-dynamic-version` installed, so I'm not sure why it's not being disabled during publish.

Hmm, did you install it with the `plugin` feature? (e.g., `poetry self add "poetry-dynamic-versioning[plugin]"`)

If you already did, then could you show me the output for these?

```
which poetry
which poetry-dynamic-versioning
poetry self show
```

**Comment by TheTechromancer** [comment]
Ah, my mistake was installing it inside the project env instead of with `self`. That fixed it, thanks!
