### ISSUE TITLE
Paramminer Error

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1275]
Got this today

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/c0d96ed0-7626-4afe-9def-a52fae1504cf)

**Comment by TheTechromancer** [comment]
Thanks for reporting. Can you post the debug.log?

**Comment by Sh4d0wHunt3rX** [comment]
Thank you 🙏 [debug.log](https://github.com/blacklanternsecurity/bbot/files/15015729/debug.log)

**Comment by Sh4d0wHunt3rX** [comment]
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/a43fd3b8-b9d2-4eed-91c4-6e80d021ad20)

**Comment by liquidsec** [comment]
Looks like the parameters that are getting parsed out of HTML are often not valid headers. I will look into adding some validation here. However, this entire system is changing down the line whenever the lightfuzz module comes out, but that might be a long time.

**Comment by liquidsec** [comment]
Will be prevented in https://github.com/blacklanternsecurity/bbot/pull/1359
