### ISSUE TITLE
Dastardly Needs to Emit "URL"

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1280]
I was checking data on a scan, and I noticed dastardly is producing finding on some URLs that they do not exist in output.ndjson

I think it's better dastardly module, generate "type": "URL" too. However, if the URL has been already generated by bbot, it ignores it (can it?), if the URL is new, it generates it. Because right now, dastardly module is producing "FINDING" for some URLs that are new and have not been produced by BBOT.

For example, this is a finding:

```
{"type": "FINDING", "id": "FINDING:acae0ac06d459c80dfb803c9caee7e778fc97c37", "data": {"host": "cdn.clickmis.net", "description": "Cross-origin resource sharing: arbitrary origin trusted found at https://cdn.clickmis.net/static/js/17.b0bf2eca.chunk.js", "url": "https://cdn.clickmis.net/static/js/17.b0bf2eca.chunk.js"}, "web_spider_distance": 1, "scope_distance": 0, "scan": "SCAN:f1bec4c3aa99562acf041c0c92752a87ef803fed", "timestamp": 1713370133.472843, "resolved_hosts": [], "source": "HTTP_RESPONSE:2da8d47dcd5e9eaa31402f0de0e73a8af7f28088", "tags": ["in-scope"], "module": "dastardly", "module_sequence": "dastardly"}
```

And this url "https://cdn.clickmis.net/static/js/17.b0bf2eca.chunk.js" not exists as "URL" in output.ndjson , so we found a potential vulnerability for a link we are not listing.

@domwhewell-sage 

Thanks 🙏

**Comment by TheTechromancer** [comment]
We are already speculating URL_UNVERIFIED events from findings. If you aren't seeing the URL, it might be because your spider settings don't allow it. 

![Screenshot_20240418-085554.png](https://github.com/blacklanternsecurity/bbot/assets/20261699/30d39064-8fe5-448d-bac4-bf152ee8c732)

**Comment by domwhewell-sage** [comment]
Thanks @TheTechromancer good spot!

**Comment by Sh4d0wHunt3rX** [comment]
Thanks a lot guys. 🙏 Is there any possibility that dastardly itself produces URL_UNVERIFIED while crawling?

Because for example my spider settings is `-c web_spider_distance=2 web_spider_depth=10`

However, dastardly for crawling won't obey this rule, right? Otherwise it couldn't emit finding on a URL that is not in our list.  So, it crawls by it's own rules but prints by bbot spider rules.

I was thinking As it crawls many links out of bbot spider rules, at least gather the list of those links and emit as URL. However, I think not possible technically maybe.

I think it needs it's own set of rules, blacklist extensions, depth .... Or maybe it not worth at all 😆

Thanks again for your explanation 🙏

**Comment by domwhewell-sage** [comment]
Hi @amiremami, we are limited in what options we can pass to dastardly, unfortunately it only accepts a start URL we cannot configure it with the same web spider rules as bbot. By default it will crawl and audit for a maximum of ten minutes.

**Comment by Sh4d0wHunt3rX** [comment]
Got it, thanks a lot 🙏
