### ISSUE TITLE
Error Parsing Dastardly XML

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1284]
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/4940ee6f-1f54-418d-8ad0-e4d67733a9f0)
[debug.log](https://github.com/blacklanternsecurity/bbot/files/15029226/debug.log)

**Comment by domwhewell-sage** [comment]
Hi @amiremami thanks for this I suspect the scan failed to start (it should log any errors with dastardly though unsure why they are not in your debug log...)
Anyhow I can look at accounting for this in the module thanks!

**Comment by Sh4d0wHunt3rX** [comment]
Hey @domwhewell-sage , have you fixed this? I just got this on v1.1.7.3268rc

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/19e08353-dbfc-4284-a182-a9ab2f3902b0)

**Comment by domwhewell-sage** [comment]
Hi @amiremami I have fixed the file not found an error but not the one from your latest screenshot. Could you send me the dastardly XML file that it is having a problem with?

**Comment by amiremami** [comment]
Thank you so much, here you are : )

[Copy of debug.log](https://github.com/blacklanternsecurity/bbot/files/15098296/Copy.of.debug.log)

**Comment by Sh4d0wHunt3rX** [comment]
Thanks a lot : )

Sure, here you are. I changed the format from xml to txt to able to upload, let me know if it didn't work like that.

[20240424_1804_29_https-int-antifraudpoc-iamanon-apps-northwesternmutual-com.txt](https://github.com/blacklanternsecurity/bbot/files/15098313/20240424_1804_29_https-int-antifraudpoc-iamanon-apps-northwesternmutual-com.txt)

**Comment by domwhewell-sage** [comment]
Thanks for the file @amiremami, I have also been able to replicate this on my end.

For my notes:
This parse error is caused by binary data being in the `CDATA` of the `text` attribute of the XML tag.

The `text` attribute isn' t required for this module however it gets parsed by `etree.parse()` so either we need to find a way to strip out the binary if it exists or see if `lxml` can handle this

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1336.
