### ISSUE TITLE
`ORG_STUB`'s raised via `-t` could be assumed out of scope by `github_org`

### ISSUE THREAD

**Issue by domwhewell-sage** [blacklanternsecurity/bbot#1286]
When running `bbot -t org:trufflesecurity -m github_org --debug` it is correctly raised as an `ORG_STUB` event and injested by the `github_org` module.

However it fails to validate that it is in scope `[VERB] github_org: Unable to validate that trufflesecurity is in-scope, skipping...`

This is because when it is looping over the profile for the org the `and` statements might not evaluate to true
```
isinstance(v, str)
and (
    self.helpers.is_dns_name(v, include_local=False)
    or self.helpers.is_url(v)
    or self.helpers.is_email(v)
)
```

There should be a way of forcing this to validate to in-scope if it has been specified as a target

**Comment by TheTechromancer** [comment]
We could consider the tags:

```python
if "target" in event.tags:
    in_scope = True
```
