### ISSUE TITLE
Pacman Ansible Tasks Fail to Update Cache

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#129]
Thanks to @j3tj3rk for finding this.

At least on arch, the ansible `package` module is doing the equivalent of `pacman -S` instead of `pacman -Sy`.

**Comment by kerrymilan** [comment]
The `package` module acts as a proxy and passes all specified options through to the actual package manager's module (`pacman`, in this case). The documentation only covers options that are common to all proxied modules, but you can achieve the desired result by setting `update_cache: yes`. 

![Screenshot_20230201_105731](https://user-images.githubusercontent.com/26632151/216095192-d8155bcc-fd85-4751-8bf4-c4c7e685cc7b.png)

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/272
