### ISSUE TITLE
Zoomeye API & Paramminer Error for HTTP Header

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1294]
I'm using my zoomeye API for the first time in bbot, however it gives me this

[INFO] Setup soft-failed for zoomeye: Error with API ('quota_info')

But I setup my API correct and it works fine outside of BBOT.

**Comment by Sh4d0wHunt3rX** [comment]
Also, if I add a custom header to my command like `http_headers={X-Request-Purpose:Research}`

`bbot -t namejet.com -m httpx paramminer_headers -c http_headers={X-Request-Purpose:Research}`

I got these

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/a158e9e4-a038-40b6-a4a3-43141a01e9e2)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/c378aeb5-37e3-4cbd-8e47-9d86f9a0c616)

**Comment by TheTechromancer** [comment]
It looks like BBOT is having trouble getting the quota info:

![image](https://github.com/blacklanternsecurity/bbot/assets/20261699/3a624fc6-5a73-4695-bfe1-355d5f823b65)

Can you try executing this request with your API key?

```bash
curl https://api.zoomeye.org/resources-info -H 'API-KEY: <your_key>'
```

**Comment by amiremami** [comment]
Here you are:

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/4de62d8d-d4ce-4b99-8b72-aeeee381e603)

**Comment by Sh4d0wHunt3rX** [comment]
Here you are:

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/7e21dbc2-8263-4e90-b9d0-7cc885d95061)

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1298. Thanks @amiremami for the quick fix!
