### ISSUE TITLE
Paramminer Error Because of Custom HTTP Header

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1299]
Hey @liquidsec : ) If I add a custom header to my command like `http_headers={X-Request-Purpose:Research}`

`bbot -t namejet.com -m httpx paramminer_headers -c http_headers={X-Request-Purpose:Research}`

I got these

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/665bef83-a20a-4313-98e1-e8e946f36a01)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/2e25478f-1900-4513-a4f3-46c2670e5a01)

Thanks 🙏

**Comment by liquidsec** [comment]
Hey @amiremami  - this is essentially identical to the issue i opened here:

https://github.com/blacklanternsecurity/bbot/issues/1225

The correct way to do it is:

```
poetry run bbot -m httpx telerik -c http_headers='{"ASP.NET_SessionId":"wezl5nvfi4ukn0f3yn4jua0a"}' -t https://nunya/
```
As I pointed out there, it's definitely counter-intuitive, and we should come up with a way to validate it and give good error messages.

I'm going to close this issue as a duplicate, but I will link to it over there.

**Comment by liquidsec** [comment]
closing as duplicate
