### ISSUE TITLE
Error (BadDNS ?)

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1301]
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/20fd0f78-1a39-49de-a713-be826e048bf2)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/1a4fc6a3-3ae7-4226-99fb-f898d052d6f6)

[debug.log](https://github.com/blacklanternsecurity/bbot/files/15094748/debug.log)

**Comment by liquidsec** [comment]
Adding to baddns issues

**Comment by liquidsec** [comment]
fixed in https://github.com/blacklanternsecurity/baddns/pull/468
