### ISSUE TITLE
Mechanism to Avoid Multiple Requests from BBOT to External APIs

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1315]
I'm using `bbot -t target.txt` and in this file, I have example.com and 2k hostnames of it. It seems hostnames enter the BBOT pool first instead of main domain, so BBOT will send a lot of API requests to third party services. That would be great if possible to implement a mechanism to prioritize the main domains first.

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/ea572447-1f11-4e5e-ac26-d9c6e850fd39)

Thanks 🙏

**Comment by TheTechromancer** [comment]
This has been implemented in BBOT 2.0.
