### ISSUE TITLE
Ignore Unresolved Events by MassDNS

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1316]
Before starting BBOT, I gather a lot of hostnames from other tools or sites. Then will add these alltogether as target. However, I noticed, unresolved events will go through massdns instead of first checking if the hostname is valid or not.

For example, here massdns is bruteforcing all those hostnames regardless of if they are valid or not. There is no DNS record for 
px29ftp2.statefarm.com

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/8d325a05-c7bf-4223-bccd-5cd0a1e15725)

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1317.

**Comment by TheTechromancer** [comment]
On second thought, it makes sense to build this on top of the massdns rewrite: https://github.com/blacklanternsecurity/bbot/pull/1303 and merge it into our BBOT 2.0 branch: https://github.com/blacklanternsecurity/bbot/pull/1235.
