### ISSUE TITLE
Zone Transfer Error

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1320]
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/61ec12d5-1a3f-4cac-8575-c20e606ac901)

**Comment by liquidsec** [comment]
This is actually baddns raising this error, I'll make in issue there to change it to a debug.

**Comment by Sh4d0wHunt3rX** [comment]
Thanks, I have also reported some issues with baddns in #1301 , however, not sure if the issue was because of it or not.

**Comment by liquidsec** [comment]
Thanks, i'll take a look at that one next. This one is fixed on Baddns side now.
