### ISSUE TITLE
problems with httpx

### ISSUE THREAD

**Issue by ngmisl** [blacklanternsecurity/bbot#1328]
**Describe the bug**
scan crashed

**Expected behavior**
scan works

**BBOT Command**
bbot -t evilcorp.com -f subdomain-enum web-basic

**OS, BBOT Installation Method + Version**
Linux, latest stable bbox
```
    "msg": "Failure downloading https://github.com/projectdiscovery/httpx/releases/download/v1.2.5/httpx_1.2.5_linux_amd64.zip, An unknown error occurred: ~/.netrc access too permissive: access permissions must restrict access to only the owner (None, line None)"
}
```

**Comment by TheTechromancer** [comment]
Thanks for reporting. Out of curiosity have you created a .netrc file? I think the error message is suggesting you need to do this to it:

```bash
chmod 700 ~/.netrc
```

**Comment by ngmisl** [comment]
> Thanks for reporting. Out of curiosity have you created a .netrc file? I think the error message is suggesting you need to do this to it:
> 
> ```bash
> chmod 700 ~/.netrc
> ```

Hm no, but i also don't understand why this is necessary

**Comment by TheTechromancer** [comment]
Having a .netrc file is uncommon and not necessary to use httpx or BBOT. If you haven't created the file, it would seem this is a bug in the httpx library.

Just to be sure, can you post the output of this command?

```bash
ls -l ~/.netrc
```

**Comment by ngmisl** [comment]
> Having a .netrc file is uncommon and not necessary to use httpx or BBOT. If you haven't created the file, it would seem this is a bug in the httpx library.
> 
> Just to be sure, can you post the output of this command?
> 
> ```shell
> ls -l ~/.netrc
> ```

-rw-rw-r-- 1 /home/user/.netrc

**Comment by TheTechromancer** [comment]
Okay it looks like you do have that file. So to fix the issue all you need to do is delete it or move it somewhere else:

```bash
mv ~/.netrc ~/.netrc.bak
```
