### ISSUE TITLE
Paramminer Error After Finishing Scan Manually

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1337]
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/83906b06-e082-4384-958e-8face01905be)

**Comment by liquidsec** [comment]
Did the scan conclude on its own or did you control+c it?

**Comment by Sh4d0wHunt3rX** [comment]
I used CTRL + C

**Comment by liquidsec** [comment]
@TheTechromancer , isn't this a more general issue with the control+c and finish()? I'm not sure I understand how that is supposed to work currently

**Comment by TheTechromancer** [comment]
Ctrl+C is a hard abort and doesn't invoke or wait for .finish(). If .finish() is being invoked after a ctrl+c, it's a bug.

That being said, the bug shown here is specific to the module. You can see from the code it's not properly aborting when it hits an error:

![Screenshot_20240504-122130.png](https://github.com/blacklanternsecurity/bbot/assets/20261699/26ba7ae1-0149-41b9-8a4c-affd55b4dc05)

**Comment by liquidsec** [comment]
HttpCompareErrors will happen fairly frequently during the scan, for example of a target goes down while it is baselining it.

I think i should probably have a continue there though

**Comment by liquidsec** [comment]
This should be addressed in https://github.com/blacklanternsecurity/bbot/pull/1359, but I don't have a reliable way to reproduce / test it.

**Comment by liquidsec** [comment]
closing until/unless issue resurfaces
