### ISSUE TITLE
Zoomeye API Error

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1344]
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/87195095-9b73-4071-800c-6847ffae9ded)

Maybe this is some kind of limitation on my plan of zoomeye?

**Comment by TheTechromancer** [comment]
Hey @amiremami, are you still experiencing this bug? Or was it due to the zoomeye domain change?

**Comment by Sh4d0wHunt3rX** [comment]
Hey : ) This was not related to domain change, as also on the screenshot, it's zoomeye.hk which is the correct one. ‌But I have not seen it so many times.

**Comment by TheTechromancer** [comment]
Okay I'm gonna close the issue for now, if it pops up again, feel free to re-open and post your `debug.log`.

**Comment by Sh4d0wHunt3rX** [comment]
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/b2932d29-2327-4d95-8b14-9d8e4b5f2702)

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1555.
