### ISSUE TITLE
Kill Multiple Modules

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1391]
I think it would be good if we can kill multiple modules at the same time, for example `kill vhost & kill ffuf`
Or instead of writing the name of them one by one, something like `skip` , so we write it and it goes directly to massdns mutation phase.

Thanks

**Comment by TheTechromancer** [comment]
Added in https://github.com/blacklanternsecurity/bbot/pull/1480.
