### ISSUE TITLE
Filedownload.handle_event (url_unverified)

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1401]
On BBOT 1.1.8 I got this, I had reported this earlier, not sure if it was fixed but yet existed or this is duplicate report.

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/40e7cb2f-181b-42bc-ac57-3ef4b820df3a)

Thanks

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1416.
