### ISSUE TITLE
Badsecrets taking a long time

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1408]
```
[DBUG]     badsecrets.finished: False
[DBUG]         running: True
[DBUG]         tasks:
[DBUG]             - badsecrets.handle_event(HTTP_RESPONSE("{'url': 'http://www.engage.tesla.com/', 'timestamp': '2024-05-28T05:36:15.965878...", module=httpx, tags={'in-scope', 'cloud-amazon', 'http-title-301-moved-permanently', 'status-301', 'ip-13-35-93-129', 'dir'})) running for 3 minutes, 52 seconds:
[DBUG]         incoming_queue_size: 111
[DBUG]         outgoing_queue_size: 0
```

**Comment by liquidsec** [comment]
If anything could be done at the badsecrets level, it would need to be demonstrably and consistently slow on the badsecrets CLI. Anything else makes me think theres something going on with the queues.

![image](https://github.com/blacklanternsecurity/bbot/assets/24899338/84b502dd-e4f8-497a-9495-75301e8b6ed4)


This happens almost instantly. Notice I even enabled redirects with -r.

I also ran badsecrets via BBOT, targeting just that domain, and its also almost instant.

Unless we can find a specific domain that is consistently taking multiple minutes, it must be outside of badsecrets itself.

**Comment by TheTechromancer** [comment]
Yeah, it's possible this was because of the excavate regexes holding up the event loop.

**Comment by TheTechromancer** [comment]
Closing for now. We can re-open if needed.
