### ISSUE TITLE
Option to Raise FILESYSTEM and WEBSCREENSHOTs as Base64 Blobs

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1421]
As suggested by @nicpenning in https://github.com/blacklanternsecurity/bbot/discussions/717

**Comment by nicpenning** [comment]
👀

**Comment by nicpenning** [comment]
Taking a crack at FILESYSTEM Base64 blobs and filedownload usage. Feel free to look at my coding attempts if you need some humor.

https://github.com/blacklanternsecurity/bbot/compare/stable...nicpenning:bbot:stable

**Comment by TheTechromancer** [comment]
> if you need some humor.

Haha looks pretty solid actually! Wanna open a draft PR?

**Comment by nicpenning** [comment]
https://github.com/blacklanternsecurity/bbot/pull/1438

**Comment by nicpenning** [comment]
Can this be closed in PR above was merged?

**Comment by TheTechromancer** [comment]
Yep I think there is still some upcoming work on this but we can close it since the feature has been added.
