### ISSUE TITLE
WPScan Installation Error

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1441]
I got this while installing bbot 

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/8c05a20e-4e12-41ca-975b-18357278a00c)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/e0afafc2-06e1-4d2b-a61e-d31c90e64a5d)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/73bb97d0-81e9-4245-8284-bda50d31a663)

**Comment by TheTechromancer** [comment]
Why tf is ruby building a native extension? Why ruby??

**Comment by Sh4d0wHunt3rX** [comment]
Also when I want to execute bbot with wpscan module
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/20cb8c5d-6417-45fc-8206-a8ca518e29c2)

**Comment by TheTechromancer** [comment]
@amiremami what's your OS?

**Comment by Sh4d0wHunt3rX** [comment]
Ubuntu 22.04

**Comment by Sh4d0wHunt3rX** [comment]
Just for clarification, I only used:
```
pipx install --pip-args '\--pre' bbot
bbot --install-all-deps
```
to install BBOT on a new Ubuntu 22.04 server as I always do.

**Comment by domwhewell-sage** [comment]
For the deps_ansible I have added back *become* and added *user_install* to false as it defaults to true
```python
{
        "name": "Install wpscan gem",
        "gem": {"name": "wpscan", "state": "latest", "user_install": False},
        "become": True,
},
```

So it should install into `/usr/bin` systemwide for all users instead of in `/root/.local/share....`

**Comment by TheTechromancer** [comment]
@amiremami did that fix work?

**Comment by Sh4d0wHunt3rX** [comment]
@TheTechromancer , I upgraded  to BBOT 1.1.9.3411rc0 and unfortunately, still can't run a scan with wpscan module.

**Comment by domwhewell-sage** [comment]
@amiremami was it the same error? / Could you post the error message

**Comment by Sh4d0wHunt3rX** [comment]
@domwhewell-sage Yes, same error, so when I add wpscan, it tries to download some stuff as visible in the screenshots. Then it shows an error 

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/d9506645-000b-4b29-85a8-7aa4225c3cdf)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/8248fe14-c387-47ef-b2eb-16ca3185f71a)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/7eeff225-1ddf-4aa8-a8ee-0e7ccf9e6029)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/1fdde48e-640e-4c72-bb44-ff7d8c21fa6e)

**Comment by Sh4d0wHunt3rX** [comment]
Seems different error though 🤔

**Comment by domwhewell-sage** [comment]
Ah yeh that's more like it. I would've thought `rubygems` would have a dependency on `ruby-devel` but I guess not! 
Thanks for testing @amiremami I'll get a fix sorted

**Comment by Sh4d0wHunt3rX** [comment]
This is fixed now, thanks : )
