### ISSUE TITLE
Optimize Neo4j

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1452]
@t94j0 I did some testing with Neo4j, and you're right that it's slow to insert events. In big scans especially, when the events are really flooding in, the Neo4j queue can get backed up.

To fix this, we'll need to figure out how to batch the cypher statements.

**Comment by TheTechromancer** [comment]
Addressed in https://github.com/blacklanternsecurity/bbot/pull/1582.

**Comment by t94j0** [comment]
Wonderful!
