### ISSUE TITLE
Scan can't start (no module named baddns)

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1512]
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/1aa36360-9b88-4f52-8c6b-e3a1e2a19e59)
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/6612dfc8-8805-4038-bc8b-e859bb2f320d)

**Comment by liquidsec** [comment]
Can you show how you are running the scan? It's complaining about you missing the `baddns` pip package, but I don't understand how you could get in that state.

Can you run with `--force-deps` first, and see if that fixes it? If not, do you see any errors when doing that?

**Comment by TheTechromancer** [comment]
Btw I think this only happens on 2.0. I wasn't able to reproduce it though

**Comment by Sh4d0wHunt3rX** [comment]
Sure here you are @liquidsec 

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/96236eba-d782-4399-98cd-4a4e68e3bbe0)

![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/d096b885-76b1-4c26-b5d3-5017b999343f)

`--force-deps` fixed it

**Comment by liquidsec** [comment]
I suspect this has something to do with you using the 2.0 branch after having previously used dev. You probably need to clean our your ~/.bbot directory, I think it was confused about which pip dependencies it had already taken care of.

**Comment by liquidsec** [comment]
@TheTechromancer same issue as https://github.com/blacklanternsecurity/bbot/issues/1508?

**Comment by Sh4d0wHunt3rX** [comment]
> I suspect this has something to do with you using the 2.0 branch after having previously used dev. You probably need to clean our your ~/.bbot directory, I think it was confused about which pip dependencies it had already taken care of.

I had removed .bbot directory, however, I installed BBOT 2 several times and last time I used `pipx reinstall bbot` , maybe because of multiple installation this issue happened. Thanks : )

Update: I uninstalled everything and install again and it's ok now.
