### ISSUE TITLE
Interactsh helper broken w/custom interactsh server

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#152]
`poetry run bbot -m httpx host_header -t <TARGET> -c interactsh_server=<customserver> interactsh_token=<customtoken>`

Results in:

`
File "/home/liquid/bbot/bbot/modules/base.py", line 261, in _setup
    result = self.setup()
  File "/home/liquid/bbot/bbot/modules/host_header.py", line 22, in setup
    self.interactsh_domain = self.interactsh_instance.register(callback=self.interactsh_callback)
  File "/home/liquid/bbot/bbot/core/helpers/interactsh.py", line 70, in register
    f"Successfully registered to interactsh server {self.server} with correlation_id {self.correlation_id} [{self.domain}]"
AttributeError: 'Interactsh' object has no attribute 'domain'
`

It appears to be skipping over activating the server if its a custom server defined in the config

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/159
