### ISSUE TITLE
Baddns Handle Event Error in BBOT2

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1522]
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/f851f5b8-1855-43bf-a744-51b2f5c49072)

**Comment by liquidsec** [comment]
Can you paste the traceback? The part i need is below the screenshot. Thx

**Comment by liquidsec** [comment]
closing this one because its a dupe with https://github.com/blacklanternsecurity/bbot/issues/1524
