### ISSUE TITLE
Whois errors still bubbling up from baddns

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1524]
As discovered by @amiremami <3

![image](https://github.com/blacklanternsecurity/bbot/assets/20261699/64f026e5-259f-4079-bf94-03f45de4faa7)

**Comment by Sh4d0wHunt3rX** [comment]
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/87c30ce6-7b51-4b91-a0fb-b45cdffc8aa8)

**Comment by liquidsec** [comment]
fixed at baddns with https://github.com/blacklanternsecurity/baddns/pull/475

**Comment by TheTechromancer** [comment]
Appears to still be happening:

![image](https://github.com/blacklanternsecurity/bbot/assets/20261699/33429a40-1327-4007-94a5-02b2ecd592ea)

**Comment by liquidsec** [comment]
This must be happening somewhere else. I'd need the full stacktrace

**Comment by TheTechromancer** [comment]
I think this is a log message from inside whois. Maybe can we silence its logger?

**Comment by Sh4d0wHunt3rX** [comment]
Maybe this helps @liquidsec 
[debug.log](https://github.com/user-attachments/files/16138541/debug.log)

**Comment by liquidsec** [comment]
> I think this is a log message from inside whois. Maybe can we silence its logger?

Yeah, that's exactly what's happening. Take a look:

https://github.com/richardpenman/whois/issues/155

**Comment by liquidsec** [comment]
@TheTechromancer i think this should fix it. Can you approve over there?

https://github.com/blacklanternsecurity/baddns/pull/476

**Comment by liquidsec** [comment]
https://github.com/blacklanternsecurity/bbot/pull/1553

**Comment by amiremami** [comment]
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/2a7e358f-ce3b-451c-a5dd-dc99eaed974e)

I got this on v2.0.0.4263rc

**Comment by Sh4d0wHunt3rX** [comment]
@liquidsec 
v2.0.0.4272rc
![image](https://github.com/user-attachments/assets/1c667996-ea56-4987-939d-0d3af538664b)

**Comment by Sh4d0wHunt3rX** [comment]
![image](https://github.com/user-attachments/assets/ec5bf18e-1b98-488d-8648-df8d4c7799df)

**Comment by Sh4d0wHunt3rX** [comment]
BBOT v2.0.0.4434rc

![image](https://github.com/user-attachments/assets/5117a6db-5313-4b6b-814e-a8e99ffda6e3)

**Comment by liquidsec** [comment]
closing for now unless we see another one. Should have been fixed with the last baddns update.

**Comment by Sh4d0wHunt3rX** [comment]
Not sure if this is related to this section, but I got this:

BBOT v2.1.0.4817rc

![image](https://github.com/user-attachments/assets/4632a32f-fe47-4785-ae01-a759d8f905c9)

**Comment by liquidsec** [comment]
> Not sure if this is related to this section, but I got this:
> 
> BBOT v2.1.0.4817rc
> 
> ![image](https://private-user-images.githubusercontent.com/15929497/373889710-4632a32f-fe47-4785-ae01-a759d8f905c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNzIxMjgsIm5iZiI6MTcyODE3MTgyOCwicGF0aCI6Ii8xNTkyOTQ5Ny8zNzM4ODk3MTAtNDYzMmEzMmYtZmU0Ny00Nzg1LWFlMDEtYTc1OWQ4ZjkwNWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDIzNDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NDBmZjQ3ZjhjNzU1Y2MwOWI2MzM2OGE1MDc2M2MyODMwZjdjMDM4ZTljNjk1NGI0ZjM3N2YwMjdhNTRlYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g7PW744SuWvwgHBy4LBWZuvLfNGtuwT7-ZEk6xjXvH8)

I am 99% sure that one is fixed if you have the latest version of baddns. If you update BBOT to dev to the latest, it should force you into the latest baddns version. let me know if you still see it after that, but I don't think you will.
