### ISSUE TITLE
Upcoming Retirement of Office 365 connectors within Microsoft Teams

### ISSUE THREAD

**Issue by domwhewell-sage** [blacklanternsecurity/bbot#1548]
I just got this warning on my teams notifications from bbot (among others)
![image](https://github.com/blacklanternsecurity/bbot/assets/122788350/071c4a4e-bf71-4d0b-824c-53d105546061)

I have my notifications setup as O365 connectors which are being depreciated as of 15th August 2024 https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/

The schema is different https://learn.microsoft.com/en-us/connectors/teams/?tabs=text1#request-body-schema so I didnt know if this might cause a problem for the teams output module in future

**Comment by domwhewell-sage** [comment]
As a test I posted this to my Teams webhook 
```json
{
  "type": "message",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "contentUrl": null,
      "content": {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.2",
        "body": [
          {
            "type": "TextBlock",
            "text": "VULNERABILITY",
            "wrap": true,
            "style": "heading"
          },
          {
            "type": "ColumnSet",
            "columns": [
              {
                "type": "Column",
                "width": "auto",
                "items": [
                  {
                    "type": "TextBlock",
                    "text": "HIGH",
                    "horizontalAlignment": "Right",
                    "spacing": "None",
                    "size": "Large",
                    "color": "Attention",
                    "wrap": true
                  }
                ]
              }
            ]
          },
          {
            "type": "ColumnSet",
            "separator": true,
            "spacing": "Medium",
            "columns": [
              {
                "type": "Column",
                "width": "stretch",
                "items": [
                  {
                    "type": "TextBlock",
                    "text": "",
                    "spacing": "Small",
                    "wrap": true
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  ]
}
```
I will open a PR to modify the current teams output module

**Comment by TheTechromancer** [comment]
Thanks I had meant to get to this sooner. Appreciate the help.

**Comment by domwhewell-sage** [comment]
No worries, I have submitted a draft PR https://github.com/blacklanternsecurity/bbot/pull/1739 which should work (I.E. its working in the designer and manually POSTing it to MS teams) Once I get back on my teams client ill test it out fully.

**Comment by domwhewell-sage** [comment]
For some reason the events accumulate into the adaptive card even though I don't get a error message from the teams output module

Edit:
It seems to be that each time `format_message()` is called it gets the adaptive card with an existing body as its defined at the class level

**Comment by domwhewell-sage** [comment]
This is working in pre-release version 2.0.1.4745rc0 so closing this issue
