### ISSUE TITLE
Error after updating to the latest version

### ISSUE THREAD

**Issue by sumgr0** [blacklanternsecurity/bbot#155]
Hi!

I'm getting the below error message when running the command:

bbot -t target.com -f subdomain-enum -m httpx -c modules.massdns.max_resolvers=500 --force -y

[ERRR] bbot.scanner.manager: Error in ScanManager._emit_event(): module 'dns.resolver' has no attribute 'LifetimeTimeout'

This was working find before the update, but crashing with that error message on every run.

Please help.

Thanks

**Comment by sumgr0** [comment]
The massdns wasn't installed. Ran the command with --retry-deps and it works now. Thanks

**Comment by sumgr0** [comment]
I guess it was to early to confirm.

The issue still persists.

**Comment by TheTechromancer** [comment]
Thanks for reporting this. What version of bbot do you have (`bbot --version`), and how did you install it?

EDIT: Would you mind also running same BBOT command with `--debug` and posting the full Python traceback. Thanks.

**Comment by sumgr0** [comment]
Hi @TheTechromancer,

I was running the version 1.0.3.777, and was finally able to resolve this after updating to the latest version 1.0.3.780 from the https://pypi.org/project/bbot/ page.

It seems to be working fine now.... after having tested it well :)

So closing this ticket. Thanks for the quick revert.
