### ISSUE TITLE
Error in Filedownload Handle Event

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1556]
![image](https://github.com/blacklanternsecurity/bbot/assets/15929497/aafc4220-d1b1-4b58-9b50-a4f23f449572)

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1555.

**Comment by amiremami** [comment]
![image](https://github.com/user-attachments/assets/d0b90fea-56ab-4d77-8311-5004a6f866a8)
