### ISSUE TITLE
SOURCE OF STORAGE_BUCKET

### ISSUE THREAD

**Issue by hishammir** [blacklanternsecurity/bbot#1564]
During a scan, I found several storage buckets. Is it possible to determine the source of these buckets and how they relate to the target domain I scanned? I checked the output.txt file, but it didn't provide any information.

```
STORAGE_BUCKET {'name': 'redacted', 'url': 'https://REDACTED.s3.amazonaws.com/'} 52.216.248.116,54.231.167.65,54.231.161.33,52.217.134.161,3.5.29.230,52.217.130.225,3.5.0.34,52.217.195.153 amazon_cloud cloud-amazon,cloud-storage-bucket,distance-1`
```

**Comment by TheTechromancer** [comment]
Yes, if you are using 2.0 (the `dev` branch), the full `discovery_path` will be in `output.json`:

```json
{
  "type": "STORAGE_BUCKET",
...
  "discovery_path": [
    "Scan overenthusiastic_stephen seeded with DNS_NAME: tesla.com",
    "bucket_azure tried 3 bucket variations of tesla.com and found STORAGE_BUCKET at https://tesla.blob.core.windows.net/tesla?restype=container"
  ]
}
```

**Comment by hishammir** [comment]
I am using v1.1.8  , any way to find the source in my current version?

**Comment by TheTechromancer** [comment]
For version 1, the easiest way is to output to neo4j. You can also look at `output.json` and manually backtrace each of the parent events using the `source` attributes.

But honestly I would recommend installing the bleeding edge version with pipx as in the readme.

**Comment by TheTechromancer** [comment]
Closing; feel free to reopen if needed.
