### ISSUE TITLE
VHOST Keeps Repeating

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1586]
I got around 20k of these vhost, same url for all.

![image](https://github.com/user-attachments/assets/db2b3937-46ec-45a5-aced-734ff49d3609)

```
{"type": "VHOST", "id": "VHOST:dc6d4b3dcefd577ff7aa66bb9e75fd16baa8aff6", "scope_description": "in-scope", "data": {"host": "www.dell.com", "vhost": "stage-jenkinscpgstwww.cdn", "url": "https://www.dell.com/"}, "host": "www.dell.com", "resolved_hosts": ["184.30.250.68", "www1.dell-cidr.akadns.net"], "dns_children": {"A": ["184.30.250.68"], "CNAME": ["www1.dell-cidr.akadns.net"]}, "web_spider_distance": 0, "scope_distance": 0, "scan": "SCAN:5ba8f0947209a7f8e2362774209cefc59b650ea9", "timestamp": 1721833597.903664, "parent": "URL:964ab8390e8f0d053e94f8d9529542e0260a210d", "tags": ["cdn-akamai", "in-scope"], "module": "vhost", "module_sequence": "vhost", "discovery_context": "vhost brute-forced virtual hosts for https://www.dell.com/ and found VHOST: stage-jenkinscpgstwww.cdn", "discovery_path": ["Scan 2024-07-24_06-52-07 seeded with DNS_NAME: dell.com", "internetdb queried Shodan's InternetDB API for \"dell.com (143.166.136.12)\" and found OPEN_TCP_PORT: dell.com:80", "httpx visited dell.com:80 and got status code 301 at http://dell.com/", "HTTP_RESPONSE was 0B with unspecified content type", "evcavate looked in \"Location\" header and found URL_UNVERIFIED: https://www.dell.com/", "httpx visited https://www.dell.com/ and got status code 302", "vhost brute-forced virtual hosts for https://www.dell.com/ and found VHOST: stage-jenkinscpgstwww.cdn"]}
```

**Comment by liquidsec** [comment]
Oh dear.

Well I suppose virtual host wildcards are a thing...

Does this happen a lot, or is this the only time you've seen it?

**Comment by Sh4d0wHunt3rX** [comment]
Hey @liquidsec sorry, I totally forgot to respond. I get like this pretty often, this is another one today:

![image](https://github.com/user-attachments/assets/59b73fc6-1c26-42b1-8a02-4c9c4113eca4)

Another one:

![image](https://github.com/user-attachments/assets/a195c4f6-b797-4047-a657-fcc3d65a239b)

**Comment by securixhk** [comment]
Hello,
I get this issue pretty often and it goes into an endless loop. Not sure how to limit the VHOST module at this level. Issue seems not controllable with _modules.vhost.lines_ module option ?

**Comment by liquidsec** [comment]
@securixhk i am about to spend some time tackling this. Do you have any logs you could provide?

**Comment by securixhk** [comment]
Hey @liquidsec 👋 , thanks a lot 🙏 , it would be very helpful 🙂 !
All the used instances have been erased and decommissioned.
Nevertheless, I think I could reproduce the issue as it was happening with random domains.
**What would be helpful for you ?** 
**debug.log or scan.log ? Or both ?** 
I would anonymize first but I guess, it's ok :).

**Comment by liquidsec** [comment]
debug.log would be best. If you can replicate it on some domains you don't mind sharing, that would be even better. If you want to send that privately we can do that too. If not, it would still be helpful.

**Comment by liquidsec** [comment]
After a little testing, it looks like the majority of the problems were coming from including "." as part of the mutations, or even if it was just within the wordlist. This resulted in multi-level subdomains, like e.cdn.whatever.com.

https://github.com/blacklanternsecurity/bbot/pull/1813

Every single example shown here was fixed by this. 

@Sh4d0wHunt3rX , or @securixhk if you have any more examples of this i definitely want to see them. But it looks like this one might be pretty simple to fix.

**Comment by securixhk** [comment]
Thanks a lot @liquidsec for this deep dive. I'll check what I can bring (if allowed for domain communication) but, as far as I remember, your finding about the dot should be very relevant :).

**Comment by liquidsec** [comment]
Im closing the issue now, but if it happens again please post here and we may reopen.

https://github.com/blacklanternsecurity/bbot/pull/1813

**Comment by securixhk** [comment]
Thanks a lot @liquidsec !!!
