### ISSUE TITLE
PassiveTotal API Works Only for Users Who Have Already Signed Up

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1589]
Passivetotal won't let new users signup on their site. Seems it still works for older users though. Maybe add a warning somewhere to let users know.

Has been reported last year on subfinder github page too.

**Comment by TheTechromancer** [comment]
Yeah they got bought out by Microsoft so I think the whole platform is being decommissioned. I think this is probably outside the scope of BBOT, at least until we add instructions into each module for how to sign up for API keys.
