### ISSUE TITLE
Help w/ File Output

### ISSUE THREAD

**Issue by brewedsec** [blacklanternsecurity/bbot#161]
Hey there!

I've been using `sudo bbot --flags subdomain-enum --targets ${site} -o Scans/bbot_out_${site} --output-modules human`
This returns the output of the scan to the folder name that I've specified above, however, instead of it only being the file, it's a random folder name that's generated and it resides inside of there.

Example: I'd like the output to go here -> `Scans/bbot_out_domain.com/output.txt`

This is what I'm getting: `Scans/bbot_out_domain.com/[RANDOM FOLDER NAME]/output.txt`

My only question that is have:
_Is there a way to only output the file without the randomly named folder that it resides in?_

I'm running this in a script, so just making an automation script here.

Thanks!!

**Comment by William-Parks** [comment]
BBOT version: v1.0.3.780

**Comment by brewedsec** [comment]
BBOT version: v1.0.3.780

**Comment by TheTechromancer** [comment]
Yes! You can accomplish this either by:
1. Choosing a custom scan `--name`
2. Redirecting the output in bash (`bbot ... | tee custom_file.txt`)

**Comment by brewedsec** [comment]
@TheTechromancer Thanks a ton!! Works like a charm.
