### ISSUE TITLE
Excavate emitting unused WEB_PARAMETERs

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1610]
Excavate seems to be emitting `WEB_PARAMETER` events even when no modules are watching for them.

Command to reproduce:

```bash
bbot -t dell.com -m dnsbrute internetdb httpx social github_org -c scope.report_distance=2 omit_event_types=[DNS_NAME_UNRESOLVED,RAW_DNS_RECORD]
```

**Comment by liquidsec** [comment]
Ok, I think this is confined to just parameters coming from set-cookie headers. Should be an easy fix.

**Comment by liquidsec** [comment]
https://github.com/blacklanternsecurity/bbot/pull/1695

**Comment by liquidsec** [comment]
fixed in https://github.com/blacklanternsecurity/bbot/pull/1695
