### ISSUE TITLE
Enhance Trufflehog module to finds Deleted & Private Commits on GitHub

### ISSUE THREAD

**Issue by domwhewell-sage** [blacklanternsecurity/bbot#1642]
**Description**
Trufflehog recently released a blog demonstrating that you could access deleted fork data on github https://trufflesecurity.com/blog/anyone-can-access-deleted-and-private-repo-data-github

They since released an update to the open-source trufflehog tool to discover hidden objects from these deleted forks. by scanning the original repo
https://trufflesecurity.com/blog/trufflehog-now-finds-all-deleted-and-private-commits-on-github

For this enhancement the trufflehog module would need to consume `CODE_REPOSITORY` events ensuring they are *github* code repositories and pass the repo url to `trufflehog github-experimental --repo <url> --object-discovery`

It would also need to be changed to access the github api token provided to the github template module

I will start working on this shortly

**Comment by TheTechromancer** [comment]
Added in https://github.com/blacklanternsecurity/bbot/pull/1644.
