### ISSUE TITLE
Setup failed for module "massdns"

### ISSUE THREAD

**Issue by Snoopy-Sec** [blacklanternsecurity/bbot#165]
![1](https://user-images.githubusercontent.com/36057801/200468088-9d9894e8-48f1-4521-950f-b9abd76a79bb.PNG)

Can u help me? MassDNS is already installed, I've also used try the option all module but this tools can`t running.

**Comment by TheTechromancer** [comment]
What OS are you running and how did you install BBOT?

**Comment by Snoopy-Sec** [comment]
I'm using windows 10 and WSL, I've tried to install using pip or poetry but options modules _-f_ can't be used

**Comment by TheTechromancer** [comment]
On Windows we've had better luck running BBOT inside docker. But if you're able to re-run that command with `--retry-deps --debug` and paste the output, we can figure out why it's failing.

**Comment by Snoopy-Sec** [comment]
![image](https://user-images.githubusercontent.com/36057801/200882486-3af51804-3859-48fb-b772-4901bc602551.png)
output, but i've tried spesific command like subdomain-enum module without `--exclude-modules massdns` this normal

**Comment by TheTechromancer** [comment]
To diagnose the problem I'll need to see the whole log in text format.

**Comment by Snoopy-Sec** [comment]
[DBUG] bbot.core.helpers.depsinstaller: {
  "hosts": "all",
  "tasks": [
    {
      "name": "install dev tools",
      "package": {
        "name": [
          "gcc",
          "git",
          "make"
        ],
        "state": "present"
      },
      "become": true
    },
    {
      "name": "Download massdns source code",
      "git": {
        "repo": "https://github.com/blechschmidt/massdns.git",
        "dest": "/home/paw/.bbot/temp/massdns",
        "single_branch": true,
        "version": "master"
      }
    },
    {
      "name": "Build massdns",
      "command": {
        "chdir": "/home/paw/.bbot/temp/massdns",
        "cmd": "make",
        "creates": "/home/paw/.bbot/temp/massdns/bin/massdns"
      }
    },
    {
      "name": "Install massdns",
      "copy": {
        "src": "/home/paw/.bbot/temp/massdns/bin/massdns",
        "dest": "/home/paw/.bbot/tools/",
        "mode": "u+x,g+x,o+x"
      }
    }
  ]
}
ansible-playbook [core 2.12.8]
  config file = None
  configured module search path = ['/home/paw/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/paw/.cache/pypoetry/virtualenvs/bbot-_0Ypd5id-py3.9/lib/python3.9/site-packages/ansible
  ansible collection location = /home/paw/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/paw/.cache/pypoetry/virtualenvs/bbot-_0Ypd5id-py3.9/bin/ansible-playbook
  python version = 3.9.15 (main, Oct 12 2022, 19:14:24) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
No config file found; using defaults
host_list declined parsing /home/paw/.bbot/cache/depsinstaller/playbook_43edac03fbde30ca81eea8cff60de37fe5a3d2b0/inventory/hosts.json as it did not pass its verify_file() method
script declined parsing /home/paw/.bbot/cache/depsinstaller/playbook_43edac03fbde30ca81eea8cff60de37fe5a3d2b0/inventory/hosts.json as it did not pass its verify_file() method
auto declined parsing /home/paw/.bbot/cache/depsinstaller/playbook_43edac03fbde30ca81eea8cff60de37fe5a3d2b0/inventory/hosts.json as it did not pass its verify_file() method
Parsed /home/paw/.bbot/cache/depsinstaller/playbook_43edac03fbde30ca81eea8cff60de37fe5a3d2b0/inventory/hosts.json inventory source with yaml plugin
Skipping callback 'awx_display', as we already have a stdout callback.
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: main.json ************************************************************
1 plays in /home/paw/.bbot/cache/depsinstaller/playbook_43edac03fbde30ca81eea8cff60de37fe5a3d2b0/project/main.json

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: paw
<localhost> EXEC /bin/sh -c 'echo ~paw && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/paw/.ansible/tmp `"&& mkdir "` echo /home/paw/.ansible/tmp/ansible-tmp-1668074617.68298-23772-5586180391910 `" && echo ansible-tmp-1668074617.68298-23772-5586180391910="` echo /home/paw/.ansible/tmp/ansible-tmp-1668074617.68298-23772-5586180391910 `" ) && sleep 0'
<localhost> Attempting python interpreter discovery
<localhost> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'python3.10'"'"'; command -v '"'"'python3.9'"'"'; command -v '"'"'python3.8'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<localhost> EXEC /bin/sh -c '/home/paw/.cache/pypoetry/virtualenvs/bbot-_0Ypd5id-py3.9/bin/python3.9 && sleep 0'
Using module file /home/paw/.cache/pypoetry/virtualenvs/bbot-_0Ypd5id-py3.9/lib/python3.9/site-packages/ansible/modules/setup.py
<localhost> PUT /home/paw/.ansible/tmp/ansible-local-23694y65w0a_p/tmpw6z8aif8 TO /home/paw/.ansible/tmp/ansible-tmp-1668074617.68298-23772-5586180391910/AnsiballZ_setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/paw/.ansible/tmp/ansible-tmp-1668074617.68298-23772-5586180391910/ /home/paw/.ansible/tmp/ansible-tmp-1668074617.68298-23772-5586180391910/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/paw/.ansible/tmp/ansible-tmp-1668074617.68298-23772-5586180391910/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/paw/.ansible/tmp/ansible-tmp-1668074617.68298-23772-5586180391910/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [install dev tools] *******************************************************
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: paw
<localhost> EXEC /bin/sh -c 'echo ~paw && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/paw/.ansible/tmp `"&& mkdir "` echo /home/paw/.ansible/tmp/ansible-tmp-1668074622.1751437-24103-254111197383579 `" && echo ansible-tmp-1668074622.1751437-24103-254111197383579="` echo /home/paw/.ansible/tmp/ansible-tmp-1668074622.1751437-24103-254111197383579 `" ) && sleep 0'
Using module file /home/paw/.cache/pypoetry/virtualenvs/bbot-_0Ypd5id-py3.9/lib/python3.9/site-packages/ansible/modules/apt.py
<localhost> PUT /home/paw/.ansible/tmp/ansible-local-23694y65w0a_p/tmp6ckovk_n TO /home/paw/.ansible/tmp/ansible-tmp-1668074622.1751437-24103-254111197383579/AnsiballZ_apt.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/paw/.ansible/tmp/ansible-tmp-1668074622.1751437-24103-254111197383579/ /home/paw/.ansible/tmp/ansible-tmp-1668074622.1751437-24103-254111197383579/AnsiballZ_apt.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S -p "[sudo via ansible, key=qthszichihexqbgltnailfglcoxhelwz] password:" -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-qthszichihexqbgltnailfglcoxhelwz ; /usr/bin/python3 /home/paw/.ansible/tmp/ansible-tmp-1668074622.1751437-24103-254111197383579/AnsiballZ_apt.py'"'"' && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/paw/.ansible/tmp/ansible-tmp-1668074622.1751437-24103-254111197383579/ > /dev/null 2>&1 && sleep 0'
[WARNING]: Updating cache and auto-installing missing dependency: python3-apt
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "allow_unauthenticated": false,
            "autoclean": false,
            "autoremove": false,
            "cache_valid_time": 0,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "fail_on_autoremove": false,
            "force": false,
            "force_apt_get": false,
            "install_recommends": null,
            "lock_timeout": 60,
            "name": [
                "gcc",
                "git",
                "make"
            ],
            "only_upgrade": false,
            "package": [
                "gcc",
                "git",
                "make"
            ],
            "policy_rc_d": null,
            "purge": false,
            "state": "present",
            "update_cache": null,
            "update_cache_retries": 5,
            "update_cache_retry_max_delay": 12,
            "upgrade": "no"
        }
    },
    "msg": "python3-apt must be installed and visible from /usr/bin/python3."
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
[DBUG] bbot.core.helpers.depsinstaller: Ansible status: failed
[DBUG] bbot.core.helpers.depsinstaller: Ansible return code: 2
[WARN] bbot.core.helpers.depsinstaller: Failed to run Ansible tasks for massdns
[WARN] bbot.core.helpers.depsinstaller: Setup failed for module "massdns"
[ERRR] bbot: Failed to install dependencies for 1 modules: massdns (--force to run module anyway)

**Comment by TheTechromancer** [comment]
Try running `sudo apt install python3-apt` and then re-running BBOT with `--retry-deps`

**Comment by Snoopy-Sec** [comment]
I`ve already installed python3-apt btw still not running

**Comment by TheTechromancer** [comment]
Is the error the same?

**Comment by Snoopy-Sec** [comment]
Yep

**Comment by man3kin3ko** [comment]
I have the same issue while running with `--flags passive` directly from `~/.local/bin` directory. Why a bruteforce option even included in passive mode?

**Comment by TheTechromancer** [comment]
@kperevoznikova good question, but the reason we include it is because it's one of our most effective subdomain enumeration modules (see here https://blog.blacklanternsecurity.com/p/subdomain-enumeration-tool-face-off), and it is legitimately passive because it only sends DNS requests.

**Comment by TheTechromancer** [comment]
@Snoopy-Sec if `apt install python3-apt` isn't working, try installing it via pip instead:
```bash
pip install python-apt
```

Or if you installed it with pipx:
```bash
pipx runpip bbot install python-apt
```

Once we figure it out I will try to push a permanent fix.

**Comment by Snoopy-Sec** [comment]
@TheTechromancer here the output, venv for 'bbot' was not found. Was 'bbot' installed with pipx?

**Comment by TheTechromancer** [comment]
> Was 'bbot' installed with pipx?

Only you can answer this question lol. How *did* you install bbot?

**Comment by Snoopy-Sec** [comment]
![2](https://user-images.githubusercontent.com/36057801/201970222-b9d9475c-4fca-4cc9-9362-919e4001766e.png)
@TheTechromancer maybe you can explain

**Comment by TheTechromancer** [comment]
From your screenshot it looks like you're running BBOT inside a poetry venv. Is that correct?

**Comment by Snoopy-Sec** [comment]
Yup

**Comment by TheTechromancer** [comment]
If you have massdns installed and in your $PATH, try `--ignore-failed-deps`.

**Comment by man3kin3ko** [comment]
> If you have massdns installed and in your $PATH, try `--ignore-failed-deps`.

Cloned massdns repo is added to $PATH and everything looks to work fine, thanks
