### ISSUE TITLE
Modules to download code repos are missing from default code-enum preset

### ISSUE THREAD

**Issue by domwhewell-sage** [blacklanternsecurity/bbot#1658]
**Describe the bug**
I have just noticed when setting up the presets for bbot 2.0 the `code-enum` preset includes the trufflehog module to search for secrets in code repositories/docker images but the modules to download those are not flaged as `code-enum` so trufflehog will never have any `FILESYSTEM` events to consume 😢 *sad-puppy-emoji .

I propose adding `git_clone`, `docker_pull` and `github_workflows` (This might have been left out but it can include secrets from your code repos)

I can add these tags to those modules

**Comment by TheTechromancer** [comment]
Oh no 😭 yes those should definitely be in that group.
