### ISSUE TITLE
Sanitizing event data Error

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1691]
![image](https://github.com/user-attachments/assets/3b5a8fdc-72a9-4a74-ac9e-2f13e173d6ea)

```
[WARN] internal.excavate: Error sanitizing event data "https://pdd.yandex.com:" for type "URL_UNVERIFIED": Invalid URL: "https://pdd.yandex.com:"

[WARN] internal.excavate: Error sanitizing event data "https://pdd.yandex.ru:" for type "URL_UNVERIFIED": Invalid URL: "https://pdd.yandex.ru:"
```

**Comment by TheTechromancer** [comment]
Fixed in 9eb9152a.

**Comment by TheTechromancer** [comment]
Fix was reversed due to concerns from @liquidsec:

> that regex was never meant to be used for extraction, if i remember right, just for validation
> ...regex wont allow query strings
> ...going to cause major issues down the line where we keep the parameter i.e. lightfuzz branch
> ...very concerned about suddenly using a validating regex as a carving regex
> ...think i just need to add some more validation to the post-yara URL processing, that is where i'd prefer to address it
> if you remove that commit i'll approve the rest of the pR

New PR: https://github.com/blacklanternsecurity/bbot/pull/1709

**Comment by Sh4d0wHunt3rX** [comment]
![image](https://github.com/user-attachments/assets/3028fe20-8710-49f2-bad8-5ebdf94867bf)

Got this one recently.

**Comment by TheTechromancer** [comment]
@liquidsec any progress on this?

**Comment by liquidsec** [comment]
@Sh4d0wHunt3rX Would you be willing to share the event chain that led to that? So if you have the JSON output from that scan, I would be able to find it

**Comment by TheTechromancer** [comment]
@liquidsec I made a branch with a new test for this issue:

https://github.com/blacklanternsecurity/bbot/pull/1709

![image](https://github.com/user-attachments/assets/6ac4828e-835e-43e6-a75b-23ad550b2e92)

**Comment by liquidsec** [comment]
fixed in https://github.com/blacklanternsecurity/bbot/pull/1709
