### ISSUE TITLE
Sanitizing Event

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1692]
![image](https://github.com/user-attachments/assets/42439412-9872-4304-a641-129c4f26c3fe)

![image](https://github.com/user-attachments/assets/ed27e8e1-ffb1-4e48-bfd5-9a1181d9e894)

**Comment by TheTechromancer** [comment]
Took a quick look at these:

![image](https://github.com/user-attachments/assets/86c8cf35-f2b1-413a-92eb-65cf858e84da)

And it seems they are both malformed data. Since they're pretty rare edge cases, I don't think it makes sense to create dedicated sanitization logic for them.
