### ISSUE TITLE
Wildcard Not Detected

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1694]
![image](https://github.com/user-attachments/assets/4239add6-0603-4e54-afe9-4207e85a2803)

```
asdasd.redirectme.netuploadswag.service-in.ssl-pems-h5alpha.walmart.cn
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1723.
