### ISSUE TITLE
Regex Issue on TLD Target List

### ISSUE THREAD

**Issue by aconite33** [blacklanternsecurity/bbot#1766]
**Describe the bug**
When using a large target list with only one top level domain, certain domains get interpreted as a TLD and the regex generation will operate on every subdomain instead of the TLD.

**Expected behavior**
Only one regex rule generated per TLD

**BBOT Command**
Example: `bbot -t ~/scans/target/subdomains.txt -p ~/scans/preset.yml -y --allow-deadly -o ~/scans/target/
`

**OS, BBOT Installation Method + Version**
Example: `Ubuntu, method install poetry, dev branch`

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1768.
