### ISSUE TITLE
GoWitness Dependency Error for Chrome

### ISSUE THREAD

**Issue by aconite33** [blacklanternsecurity/bbot#1767]
**Describe the bug**
When running BBoT Dev with gowitness module, encountering error for .so files not being installed.

**Expected behavior**
Running a bbot scan with gowitness module without error

**BBOT Command**
`bbot -m gowitness -t target.com`

**OS, BBOT Installation Method + Version**
`Ubuntu 24.04, poetry install, bbot-dev branch`

**Screenshots**
![image](https://github.com/user-attachments/assets/40535264-3694-4ea1-9d40-ac66a7973f0e)

**Comment by aconite33** [comment]
In order to get this to work on Ubuntu, the following packages were installed:

```
libatk1.0-dev
libatk-bridge2.0-dev
libcups2-dev
libxcomposite-dev
libxdamage-dev
libxrandr-dev
libgbm-dev
libpango1.0-dev
libasound2-dev
```

**Comment by HotSpoon-ColdMango** [comment]
I also am getting a similar error when attempting:
![image](https://github.com/user-attachments/assets/0255eca0-702f-4786-9555-56c6d63eb7ba)

**Comment by TheTechromancer** [comment]
@aconite33 to set up tests for this, we need self-hosted runners.

**Comment by TheTechromancer** [comment]
Testing this on ubuntu `24.04`, the package `libasound2` doesn't exist like it does on `22.04`:

```
Package 'libasound2' has no installation candidate\n"
```

Probably we should be using something like flatpak, so we don't have to try and stay on top of all these crazy os dependencies, which are gonna be different on every distro (and even between different versions of the same distro).

**Comment by TheTechromancer** [comment]
This is fixed now (we have tests for it)
