### ISSUE TITLE
can bbot be configured to keep prev state of scan where it was stopped?

### ISSUE THREAD

**Issue by Abhinavpatel00** [blacklanternsecurity/bbot#1771]
**Description**
Which feature would you like to see added to BBOT? What are its use cases?
i would love to have a features if for some reason we have to stop in the middle of scan then when we run scan again , instead of doing it everything from start , it should continue from where it left

**Comment by Sh4d0wHunt3rX** [comment]
Hey : ) I guess it can be related to #826

**Comment by TheTechromancer** [comment]
Closing as this has already been answered in  https://github.com/blacklanternsecurity/bbot/discussions/826.
