### ISSUE TITLE
Docker_Pull Could not retrieve all tags

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1780]
Not sure if this need to report or no. BBOT v2.0.1.4720rc

![bbot](https://github.com/user-attachments/assets/472dfa2d-a913-43f3-9bb1-81db5931478a)
![image](https://github.com/user-attachments/assets/adc12c1a-fedc-4a8f-9439-46321af591c5)

**Comment by domwhewell-sage** [comment]
This is an intended error message as its not getting a 200 OK response from the /tags/list registry endpoint

**Comment by Sh4d0wHunt3rX** [comment]
Thank you so much 🙏 I'm not sure, but maybe emit it as WARNING? I think everything with ERRR label is a bug in BBOT and needs to be fixed, but again, I'm too noob to give opinion about this. Maybe @TheTechromancer can check and close the thread if it's ok.

**Comment by TheTechromancer** [comment]
Yes that's true. Typically if it's unexpected and needs the user's attention it should be a warning. Otherwise if it's a more common occurrence it should probably be verbose/debug.

**Comment by domwhewell-sage** [comment]
Oh yeh, good point I have also logged the response status in a debug message
