### ISSUE TITLE
pipx install has no versions available

### ISSUE THREAD

**Issue by jsarkisian** [blacklanternsecurity/bbot#18]
Tried installing from pipx and got this:

```
root@box:~# pipx install bbot
ERROR: Could not find a version that satisfies the requirement bbot (from versions: none)
ERROR: No matching distribution found for bbot
```
Anything I can do on my end?

**Comment by TheTechromancer** [comment]
As stated in the [wiki](https://github.com/blacklanternsecurity/bbot/wiki#troubleshooting), you need to make sure your Python version is 3.9 or higher.

**Comment by jebat8101** [comment]
use pip

> Tried installing from pipx and got this:
> 
> ```
> root@box:~# pipx install bbot
> ERROR: Could not find a version that satisfies the requirement bbot (from versions: none)
> ERROR: No matching distribution found for bbot
> ```
> 
> Anything I can do on my end?

use pip

**Comment by TheTechromancer** [comment]
> use pip

This is not recommended except inside a virtualenv, since certain BBOT modules install additional Python dependencies that may conflict with your existing ones. The purpose of installing it with `pipx` is to cleanly isolate BBOT in its own environment.

**Comment by TheTechromancer** [comment]
Closing this issue for now. Please comment if you have additional questions or if your solution was different from the one mentioned in the wiki.
