### ISSUE TITLE
`-om json` different in v2 ?

### ISSUE THREAD

**Issue by ocervell** [blacklanternsecurity/bbot#1805]
`bbot` used to output JSON lines directly to the terminal so we could pipe results it with `jq` directly:

```
bbot -t <TARGET> -om json | jq '.'
```

It seems that the behavior has changed in v2, now it saves JSON lines to a file, so we can't pipe `bbot`'s output directly anymore. It also means we lost the 'yield in realtime' feature of `bbot` since now we have to wait till the end of the scan to read the JSON file.

Is it wanted behavior ? Is there a flag I missed to re-enable streaming JSON lines directly to stdout ?

**Comment by TheTechromancer** [comment]
> Is there a flag I missed to re-enable streaming JSON lines directly to stdout ?

`--json`
