### ISSUE TITLE
Trufflehog Processing Error

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1822]
BBOT v2.1.0.4817rc

![image](https://github.com/user-attachments/assets/29a163d8-d9aa-40ee-833c-fd7162a34a30)

**Comment by domwhewell-sage** [comment]
This is an error from trufflehog itself, I'm not sure there's a lot we can do aside from reporting it to the trufflehog repository

Edit: It seems this issue has already been reported https://github.com/trufflesecurity/trufflehog/issues/2877

**Comment by TheTechromancer** [comment]
Closing this for now
