### ISSUE TITLE
failing to install some modules on macos (apple silicon), caused by wrong binary name.

### ISSUE THREAD

**Issue by Giardi77** [blacklanternsecurity/bbot#1823]
![Screenshot 2024-10-06 at 02 53 48](https://github.com/user-attachments/assets/7859d795-dc74-4c54-b59b-8bca23293798)

this is due to the fact that the binary name on the trufflehog release repo is not "trufflehog_3.75.1_macOS_arm64.tar.gz" but "trufflehog_3.75.1_darwin_arm64.tar.gz"

![Screenshot 2024-10-06 at 02 54 17](https://github.com/user-attachments/assets/e3f043b3-4d51-4e31-8602-efa1ec6b9527)

**Comment by TheTechromancer** [comment]
Thanks for reporting. Bugfix is here: https://github.com/blacklanternsecurity/bbot/pull/1825.

Note that we don't technically support MacOS; so it's highly recommended to run BBOT inside docker.

**Comment by Giardi77** [comment]
Oh ok i will use docker from now on, btw thanks for the almost instant bugfix.
