### ISSUE TITLE
Generic SSRF XXE payload error

### ISSUE THREAD

**Issue by aroly** [blacklanternsecurity/bbot#1830]
Hello,

I was taking a look at the Generic SSRF module and spotted an error in the "Generic XXE" class. The XXE payload used is: 

https://github.com/blacklanternsecurity/bbot/blob/b169b140df5db8040d3c8f33bcb183bf770ff42e/bbot/modules/generic_ssrf.py#L138-L142

The `%` character in `<!ENTITY % {rand_entity}` is not correct in that case, and you should remove it if you use the entity in the XML body. 

Regards,

A.

**Comment by liquidsec** [comment]
Hi, @aroly. Nice catch on this. Although I think on some platforms this still triggered an interaction, it is definitely not correct and at least on PHP where I just re-tested it was broken.

I also fixed another bug I found during testing where the incorrect URL was sometimes used.

https://github.com/blacklanternsecurity/bbot/pull/1870
