### ISSUE TITLE
Failed scan when using --strict-scope and stdout output module

### ISSUE THREAD

**Issue by aconite33** [blacklanternsecurity/bbot#1854]
**Describe the bug**
Encountered an error when scanning a list of targets

**Expected behavior**
Completion of the scan

**BBOT Command**
Example: `bbot -t targetlist.txt -o ~/scans/ -y --allow-deadly --strict-scope -em excavate dnsresolve cloudcheck -m dotnetnuke -om txt csv json stdout`

**OS, BBOT Installation Method + Version**
Example: `Ubuntu 20.04, Dev version (10/15/2024)`

**Screenshots**
![image](https://github.com/user-attachments/assets/129b270e-84c4-4b06-8185-38fcfa5b79fd)

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/commit/e81a549e7a45307b47c256bbfef3df78f373e6aa.
