### ISSUE TITLE
Third-party API keys not properly loaded from secrets.yml when using presets

### ISSUE THREAD

**Issue by mikismaos** [blacklanternsecurity/bbot#1862]
**Describe the bug**
Some of the API keys that had been provided in `secrets.yml` were not recognized when running the `subdomain-enum` preset. Specifically, "chaos", "securitytrails" and "github_codesearch". 
![api3](https://github.com/user-attachments/assets/9afc42b1-2fbc-4c5f-ae13-93e60ba7512b)

**Expected behavior**
The relevant modules should use the provided API keys, especially since they were indeed recognized when trying them out individually (e.g. `bbot -t evilcorp.com -m chaos`). 
![api2](https://github.com/user-attachments/assets/4f587162-31dc-42fd-8980-68d259a3ff35)

**BBOT Command**
`bbot -t evilcorp.com -p subdomain-enum`

**BBOT Config**
I used the default configs, I only edited `secrets.yml`.
![api1](https://github.com/user-attachments/assets/83f0fdd3-992c-4e0b-8b34-7598c6a17ed5)

**System details**
OS: Kali Linux (Linux kali 6.8.11-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.8.11-1kali2 (2024-05-30) x86_64 GNU/Linux)
BBOT: v2.0.1
Python: 3.12.6

**Comment by TheTechromancer** [comment]
Thanks for the report. I'll be looking into this one.

**Comment by TheTechromancer** [comment]
This looks like it's happening because of the API key placeholders we have in the subdomain-enum preset:

![Screenshot_20241017-092613.png](https://github.com/user-attachments/assets/2af39c11-26f9-47f5-a42a-7e8e40aa1676)

For now, you can comment out those lines and it should work for you.

**Comment by mikismaos** [comment]
Thanks for the response. 

That didn't do the trick for some reason. Neither commenting out the lines, nor setting my API keys inside `subdomain-enum.yml` worked. 

![api7](https://github.com/user-attachments/assets/610a3851-e3f6-44f9-92cc-162e8dacf7d3)
![api6](https://github.com/user-attachments/assets/1fb885eb-5076-4613-9048-8d7b242e7b16)

The only thing that worked was setting the keys via command line argument ("-c"):
`bbot -t evilcorp.com -p subdomain-enum -c modules.github_codesearch.api_key=[redacted] modules.securitytrails.api_key=[redacted] modules.chaos.api_key=[redacted]`

**Comment by TheTechromancer** [comment]
What's the output of:

```bash
ls -lah ~/.bbot/presets
```

**Comment by TheTechromancer** [comment]
In my testing this bug has been fixed in https://github.com/blacklanternsecurity/bbot/pull/1857. Feel free to reopen the issue if you're still experiencing it.
