### ISSUE TITLE
Can't explicitly exclude module enable by preset

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#1866]
If the module is being explicitly added in the preset, like:

```
modules:
  - ffuf
  - wayback
```

The scan will just abruptly cancel with this error, if you try to remove it with `-em <module>`

```
Unable to add scan module "wayback" because the module has been excluded
```

Example:

![image](https://github.com/user-attachments/assets/3873557b-0cae-46f9-91e1-e557dcff5962)

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1872.
