### ISSUE TITLE
Support for custom headers

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#187]
Support for adding custom headers to outgoing requests. These would need to be proxied down into the various elements of bbot that interact directly with web assets, like the request helper, httpx, curl, nuclei, gowitness, etc. 

by default they should be scoped to the scan targets/whitelist, but support for more strict domain scoping should be provided.

Possible points of input are either the config system or as a separate CLI variable, or both

**Comment by TheTechromancer** [comment]
Added in https://github.com/blacklanternsecurity/bbot/pull/251
