### ISSUE TITLE
v2.1.2.5161rc Errors

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1931]
![image](https://github.com/user-attachments/assets/656da79d-4c74-4ae0-a5f8-c37a24b414d4)
![image](https://github.com/user-attachments/assets/b264e657-8c0f-4f1f-8bf0-50d80c2af5a4)
![image](https://github.com/user-attachments/assets/b7d15928-0c01-4e01-8a43-8acd03028fbc)

Seems killing not works

![image](https://github.com/user-attachments/assets/89e253c2-33e7-4e1b-bd7b-6fb637745113)
![image](https://github.com/user-attachments/assets/7cc83cd3-b417-4cff-aef1-20915537787a)

CTRL+C didn't end gracefully. However, with several ctrl+c it finished the job, just an error at the end:

![image](https://github.com/user-attachments/assets/7697ad31-fe86-449c-80e1-4374c21e5f29)

Thanks 🙏

**Comment by TheTechromancer** [comment]
Thanks, these are fixed in https://github.com/blacklanternsecurity/bbot/pull/1899/commits/b98adbec223100d08b51bebc5ee383f7c1dd6266.
