### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by tycoonslive** [blacklanternsecurity/bbot#195]
Hi team,
Nice work that I discover...
While browsing through the modules, I saw that an IP geolocation was missing which could be an additional asset to your tool which has already convinced me

**Comment by TheTechromancer** [comment]
@tycoonslive good idea! If you want to take a stab at this I recommend looking at [this wiki section](https://github.com/blacklanternsecurity/bbot/wiki#writing-modules) on how to write a module. We encourage contributions and we're happy to help you through the process.

**Comment by tycoonslive** [comment]
Ok, I just tested the creation of a module with the doc.
But it doesn't seem to work.
I added a field in the API key file to put the key
I then created my module in the /modules folder
named ipstack.py
Where can I show you this so you can tell me where I'm going wrong
      ` from bbot.modules.base import BaseModule
    
    class Ipstack(BaseModule):
        """
        Ipstack GeoIP
        Leverages the ipstack.com API to geolocate a host by IP address.
        """
    watched_events = ["IP_ADDRESS"]
    produced_events = ["IP_ADDRESS"]
    flags = ["subdomain-enum", "passive", "safe"]
    meta = {"description": "Query IPStack's API for GeoIP ", "auth_required": True}
    options = {"api_key": ""}
    options_desc = {"api_key": "IPStack GeoIP API Key"}

    base_url = "http://api.ipstack.com/"

    def setup(self):
        self.processed = set()
        self.ratelimit = int(self.config.get("ratelimit", 0.8,False))
        self.api_key = self.config.get("api_key", "")
        if self.api_key :
            try:
                self.ping()
                self.hugesuccess(f"API is ready")
                return True
            except Exception as e:
                return None, f"Error with API ({str(e).strip()})"
        else:
            return None, "No API key set"
    
    def filter_event(self, event):
        if str(event.module) in ("speculate", "ipstack"):
            return False
        return True

    def ping(self):
        r = self.helpers.request(f"{self.base_url}/check?access_key={self.api_key}")
        resp_content = getattr(r, "text", "")
        assert getattr(r, "status_code", 0) == 200, resp_content`
Here is what I did for the beginning after I am a little lost in the queries and the handler

**Comment by TheTechromancer** [comment]
Nice work. Basically all the juicy stuff happens in the `handle_event()` function. Here's a working example that still needs a little work.

```python
from .shodan_dns import shodan_dns


class Ipstack(shodan_dns):
    """
    Ipstack GeoIP
    Leverages the ipstack.com API to geolocate a host by IP address.
    """
    watched_events = ["IP_ADDRESS"]
    produced_events = ["GEOLOCATION"]
    flags = ["passive", "safe"]
    meta = {"description": "Query IPStack's API for GeoIP ", "auth_required": True}
    options = {"api_key": ""}
    options_desc = {"api_key": "IPStack GeoIP API Key"}
    scope_distance_modifier = 0
    suppress_dupes = False
    
    base_url = "http://api.ipstack.com/"
    
    def ping(self):
        r = self.helpers.request(f"{self.base_url}/check?access_key={self.api_key}")
        resp_content = getattr(r, "text", "")
        assert getattr(r, "status_code", 0) == 200, resp_content

    def handle_event(self, event):
        try:
            url = f"{self.base_url}/{event.data}?access_key={self.api_key}"
            result = self.helpers.request(url)
            if result:
                json = result.json()
                if json:
                    location = json.get("country_name")
                    self.emit_event(location, "GEOLOCATION", event)
                else:
                    self.verbose(f"No JSON response from {url}")
            else:
                self.verbose(f"No response from {url}")
        except Exception:
            import traceback

            self.verbose(f"Error retrieving results for {event.data}")
            self.debug(traceback.format_exc())
```

I made a few small modifications:
- inheriting from shodan_dns (so we don't have to write our own `setup()` function)
- `scope_distance_modifier = 0`: this says to accept events that are 1 hop away from the target (e.g. IP addresses that are reverse-resolved from DNS names)
 - `suppress_dupes = False`: this stops BBOT from deduplicating the modules' results, so we can get a result like this:
 
![image](https://user-images.githubusercontent.com/20261699/203878702-f99dcbb7-3e88-4dbf-b455-0388af8a9415.png)

**Comment by tycoonslive** [comment]
Thank you for your reply.
I still have a question about the outputs.
In the TXT files we do not see "GEOLOCATION" and in IP_ADDRESS no info, I would like to understand how to create this output before modifying your code which has already helped me a lot to understand the operation.
exemple output now :
[IP_ADDRESS]            1.2.3.4  A       (distance-1, ipv4, ptr-record, resolved)
I'm trying to produce this on output :
[IP_ADDRESS]            1.2.3.4  country city...      
Well, I understand that I should have a GEOLOCATION instead of IP_ADDRESS
thanks

**Comment by TheTechromancer** [comment]
You should see the GEOLOCATION events once you put the code in `bbot/modules/ipstack.py` and also put the API key in `~/.config/bbot/secrets.yml`:

```yaml
modules:
  ipstack:
    api_key: deadbeef
```

You can also pass the API key on the command line like so: `--config modules.ipstack.api_key=deadbeef`.

**Comment by tycoonslive** [comment]
Hello,
the key has been added no problem just the outputs not working but I don't see anything in the output.txt file
Thank you for the time you spend with me, but I want to have a good understanding of your code 
I just created a fork with the embedded code to show you

**Comment by TheTechromancer** [comment]
The first argument to `emit_event()` needs to be a string, e.g.:
```python
self.emit_event(f"{location}, {city}, {latitude}, {longitude}", ...)
```

![Screenshot_20221126-110900.png](https://user-images.githubusercontent.com/20261699/204098077-143898df-b025-494c-8a83-f7ac77fc62d1.png)

**Comment by tycoonslive** [comment]
Thanks a lot for your help, tested and working.
I can now see how to create a module more clearly.
Long life to this project
you can close this topic

**Comment by TheTechromancer** [comment]
Glad to help @tycoonslive, when you're finished please don't forget to make a pull request ;)

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @tycoonslive)
