### ISSUE TITLE
Is this a fork from SpiderFoot ? 

### ISSUE THREAD

**Issue by izdrail** [blacklanternsecurity/bbot#1953]
**Question**
Question: Is this a fork from Spiderfoot ?

**Comment by TheTechromancer** [comment]
BBOT is not a fork of Spiderfoot, but its recursive design is inspired by Spiderfoot's. I was a Spiderfoot dev for a while before I decided to start fresh and make BBOT :)

**Comment by izdrail** [comment]
Hey man really appreciate the answer 
I noticed the inspiration, hence the question.
I guess it shouldn't be that hard to migrate some of the modules?

**Comment by TheTechromancer** [comment]
Yes the modules are very similar. There are a few differences, e.g. BBOT is async. But tbh most of the time cursor can stamp out a working module pretty quick if you give it similar ones as examples.

**Comment by izdrail** [comment]
Thanks for the reply.
I will give it a go then by implementing a new module.

**Comment by TheTechromancer** [comment]
Awesome 👍 ping us if you have more questions. Closing the issue.
