### ISSUE TITLE
Enable shell access in docker

### ISSUE THREAD

**Issue by esirK** [blacklanternsecurity/bbot#1959]
**Description**
Although the `docker run -it blacklanternsecurity/bbot` works, it is pre-set to always run `bbot`. 
It would be nice to instead get a shell from where you can play around with all `bbot` commands.

**Comment by TheTechromancer** [comment]
Good suggestion. This should be possible by overriding the entry point like so: 

```bash
docker run --entrypoint /bin/bash blacklanternsecurity/bbot
```

Let me know if that works

**Comment by esirK** [comment]
> Good suggestion. This should be possible by overriding the entry point like so:
> 
> ```shell
> docker run --entrypoint /bin/bash blacklanternsecurity/bbot
> ```
> 
> Let me know if that works

Yeah this works. Thanks. I think just `-it` is missing.

```
docker run  --entrypoint /bin/bash -it blacklanternsecurity/bbot
```
