### ISSUE TITLE
document the secrets file

### ISSUE THREAD

**Issue by peterclemenko** [blacklanternsecurity/bbot#196]
The secrets file needs proper documentation for setup/use

**Comment by TheTechromancer** [comment]
The secrets file is covered in the readme and in the wiki. Did you have a specific question about it?

![Screenshot_20221123-194027.png](https://user-images.githubusercontent.com/20261699/203669505-7b1935c9-2749-4be6-86a7-978774cce378.png)

**Comment by tycoonslive** [comment]
pipx install bbot
bbot --config
after running the commands the path is displayed
works like a charm
path for modules /usr/local/lib/python3.10/dist-packages/bbot/
