### ISSUE TITLE
Module install fails due to git password prompt.

### ISSUE THREAD

**Issue by ObscenityIB** [blacklanternsecurity/bbot#1961]
Saw the bsides talk and decided to try this one out!

**Describe the bug**
I have a global git configuration that forces all clones/pulls/pushes etc to use SSH instead of HTTP(S).
This causes bbot to fail some module installs that it pulls from git repos, as it doesn't prompt for the password.

**Expected behavior**
bbot interactively asks for the git ssh password, similar to how it asks for elevation when starting the module installs

**BBOT Command**
`bbot -t intranet.local -p kitchen-sink --allow-deadly -v --retry-deps -d`

**OS, BBOT Installation Method + Version**
OS: Arch Linux
Installation method: venv + pip
BBOT version: v2.1.2.5223rc

**BBOT Config**
Default

**Logs**
relevant bbot log:
```
        "res": {
            "cmd": "/usr/bin/git ls-remote https://github.com/blechschmidt/massdns.git -h refs/heads/master",
            "rc": 128,
            "stdout": "",
            "stderr": "git@github.com: Permission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n",
            "msg": "git@github.com: Permission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.",
...
[ERRR] Failed to install dependencies for 2 modules: dnsbrute,dnsbrute_mutations (--force to run module anyway)
```
.gitconfig layout
```
[user]
	name = ObscenityIB
	email = ***
	signingkey = ***
[includeIf "gitdir:~/DEV/gitea/"]
    path = ~/DEV/gitea/.gitconfig
[includeIf "gitdir:~/DEV/opengist/"]
    path = ~/DEV/opengist/.gitconfig
# Enforce SSH
[url "ssh://git@github.com/"]
  insteadOf = https://github.com/
[url "ssh://git@gitlab.com/"]
  insteadOf = https://gitlab.com/
[url "ssh://git@bitbucket.org/"]
  insteadOf = https://bitbucket.org/
[url "ssh://git@intranet.local:222/"]
  insteadOf = http://intranet.local:3000/
[url "ssh://git@intranet.local:2222/"]
  insteadOf = http://intranet.local:6157/
[commit]
	gpgsign = true
```
---
Yes, I could totally just, not do this, but I'm definitely not the only one out there that enforces ssh for git, so a fix in place would benefit others as well.

That fix could be as simple as using a different, possibly empty, .gitconfig in bbot's environment, preventing it from getting stuck by the users preferences.

**Comment by TheTechromancer** [comment]
Thanks for reporting. Hopefully this should be an easy fix.

**Comment by TheTechromancer** [comment]
Added a fix for this in https://github.com/blacklanternsecurity/bbot/pull/1962. 

Would you mind testing it? You can `pip install git+https://github.com/blacklanternsecurity/bbot@fix-git-bug`

@ObscenityIB

**Comment by ObscenityIB** [comment]
Confirmed working, thanks for the fix.
