### ISSUE TITLE
cli.py error

### ISSUE THREAD

**Issue by timlaw71** [blacklanternsecurity/bbot#203]
I am getting this error when I try to run bbot.

 bbot: Encountered unknown error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bbot/cli.py", line 225, in main
    input()
EOFError: EOF when reading a line

**Comment by TheTechromancer** [comment]
Thanks for the report, can you post your:

- full BBOT command
- BBOT `--version`
- OS

**Comment by timlaw71** [comment]
docker run blacklanternsecurity/bbot:stable -o . --output-module human csv -f subdomain-enum -t domain_name

[INFO] bbot: Loaded defaults from /usr/local/lib/python3.10/site-packages/bbot/defaults.yml
[INFO] bbot: Creating BBOT config at /root/.config/bbot/bbot.yml
[INFO] bbot: Creating BBOT secrets at /root/.config/bbot/secrets.yml
v1.0.3.780

Linux kali 6.0.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.7-1kali1 (2022-11-07) x86_64 GNU/Linux

**Comment by timlaw71** [comment]
[ERRR] bbot: Encountered unknown error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bbot/cli.py", line 225, in main
    input()
EOFError: EOF when reading a line

**Comment by TheTechromancer** [comment]
Ah okay, try `docker run -it ...`

**Comment by timlaw71** [comment]
That works. Thanks

**Comment by TheTechromancer** [comment]
Todo: Update readme, check `stdin.isatty()`.

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/207
