### ISSUE TITLE
error while loading shared libraries: libglib-2.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by fuomag9** [blacklanternsecurity/bbot#2058]
**Describe the bug**
error while loading shared libraries: libglib-2.0.so.0: cannot open shared object file: No such file or directory

**Expected behavior**
No error

**BBOT Command**
`docker run -it --rm -d -v /var/run/docker.sock:/var/run/docker.sock -t 1.1.1.1/24  -p kitchen-sink`

**OS, BBOT Installation Method + Version**
ubuntu 22.04, lxc

**Logs**
```
[WARN] Stderr for run(/root/.bbot/tools/chrome-linux/chrome --version):
	/root/.bbot/tools/chrome-linux/chrome: error while loading shared libraries: libglib-2.0.so.0: cannot open shared object file: No such file or directory

[WARN] Setup hard-failed for gowitness: Failed to set up Google chrome. Please install manually or try again with --force-deps.
[WARN] gowitness: Setting error state
[INFO] Setup soft-failed for github_workflows: Error with API ({
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest",
  "status": "401"
})
[INFO] Setup soft-failed for github_org: Error with API ({
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest",
  "status": "401"
})
[INFO] Setup soft-failed for git_clone: Error with API ({
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest",
  "status": "401"
})
[ERRR] Setup hard-failed for 1 modules (gowitness) (--force to run module anyway)
```

**Comment by TheTechromancer** [comment]
@fuomag9 thanks for reporting. We'll look into it

**Comment by TheTechromancer** [comment]
Gowitness in docker is working fine for me.

![image](https://github.com/user-attachments/assets/fc5256d4-7e3f-4586-9770-36ededd48103)

I noticed in your installation method you have `lxc`, but in your bbot command you're using `docker`. But also that your docker command is missing the image name.  Can you post the full commands you used to install + launch bbot?

**Comment by fuomag9** [comment]
@TheTechromancer I'm using docker inside an LXC container, these are the info for reproducing this correctly:

This will make the error appear:
`docker run -it --rm -d -v /var/run/docker.sock:/var/run/docker.sock -v ./tmp/blankfolder:/root/.bbot/  blacklanternsecurity/bbot -t 1.1.1.1/24  -p kitchen-sink --allow-deadly -y`

While this will not:
`docker run -it --rm -d -v /var/run/docker.sock:/var/run/docker.sock  blacklanternsecurity/bbot -t 1.1.1.1/24  -p kitchen-sink --allow-deadly -y`

Btw, is there an official way to obtain output data from the container?

**Comment by TheTechromancer** [comment]
Oh I see. The problem is that the `.bbot` directory contains a cache that remembers which dependencies have been installed. So when you persist it between containers, it will mistakenly skip installing dependencies because it thinks they've already been installed.

Probably the best solution is to map `.bbot/scans` instead.

**Comment by TheTechromancer** [comment]
> Btw, is there an official way to obtain output data from the container?

Technically yes, there is a bash script [`bbot-docker.sh`](https://github.com/blacklanternsecurity/bbot/blob/stable/bbot-docker.sh) although right now it has the same problem as above. 

But mapping `.bbot/scans` is basically the "official" way retrieve scan output.

**Comment by TheTechromancer** [comment]
@fuomag9 are we good to close this out?

**Comment by fuomag9** [comment]
> @fuomag9 are we good to close this out?

Sure! Maybe it would make sense to add this information to the documentation?

**Comment by TheTechromancer** [comment]
https://www.blacklanternsecurity.com/bbot/Stable/#docker
