### ISSUE TITLE
deps commands possibly not working

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#2077]
Disclaimer - I'm on lightfuzz branch and haven't tested elsewhere

--retry-deps, --ignore-failed-deps, and --force-deps appear to be non-functional. 

one example screenshot with --ignore-failed-deps. It would not starts the scan. Had to manually delete the deps cache:

![image](https://github.com/user-attachments/assets/90f7c496-198e-4e50-921f-c9a44018f3dd)

**Comment by TheTechromancer** [comment]
Confirmed this is an issue in dev

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/2087.
