### ISSUE TITLE
Can you make naabu module be config

### ISSUE THREAD

**Issue by L4ml3da** [blacklanternsecurity/bbot#208]
Sometimes，the bbot module naabu cannot find host port. For example, I'd like to set naabu '-Pn' options, but the config not support.
Or, Can you show the way of complie. I will modify the file "naabu.py"  and compile by myself.

**Comment by TheTechromancer** [comment]
The naabu module supports specfying the top ports or a manual list of ports. Is there another option you were looking for specifically? There is no `-Pn` option that I know of; that's for nmap.

By default it scans the top 100 ports. If you want to specify ones, you can set them in your bbot config (`~/.config/bbot/bbot.yml`) or on the command line like this:
```bash
bbot -m naabu -c modules.naabu.ports=80,443
```

Note that you can list a module's options like this:
```bash
bbot -m naabu --help-all
```

**Comment by TheTechromancer** [comment]
I was able to confirm that naabu was missing ports. It is much more accurate when running as root, so I made the fix. Closing this issue.
