### ISSUE TITLE
BBOT Error, Not Possible to Start Scan

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#2085]
![image](https://github.com/user-attachments/assets/b0dde33b-ef10-4edc-b3ee-2d489f5d7fe0)

**Comment by TheTechromancer** [comment]
What branch/version of BBOT are you on?

**Comment by Sh4d0wHunt3rX** [comment]
Dev v2.3.0.5467rc

**Comment by TheTechromancer** [comment]
Nice catch @Sh4d0wHunt3rX. Fixed + test added in https://github.com/blacklanternsecurity/bbot/pull/2086.
