### ISSUE TITLE
Cloudcheck Handle Event Error

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#2090]
![image](https://github.com/user-attachments/assets/d8af09b6-00d8-4f3b-b337-0202b3ca8c80)

![image](https://github.com/user-attachments/assets/882a91e2-ba4a-432f-bab7-3b0414e6db2f)

**Comment by Sh4d0wHunt3rX** [comment]
![image](https://github.com/user-attachments/assets/190c513d-e298-401a-acac-cb0b0f25af13)

**Comment by Sh4d0wHunt3rX** [comment]
![image](https://github.com/user-attachments/assets/c8afa171-b901-4f5d-8850-ca4f9ab4f3c8)

**Comment by TheTechromancer** [comment]
![image](https://github.com/user-attachments/assets/584d10b3-041f-4215-8f77-3df596c78fbb)

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/2108.
