### ISSUE TITLE
Gowitness Naming Error

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#2091]
![image](https://github.com/user-attachments/assets/b7d1507f-547d-4ad2-964e-45bd42f72c39)

**Comment by TheTechromancer** [comment]
Duplicate of https://github.com/blacklanternsecurity/bbot/issues/1557

**Comment by TheTechromancer** [comment]
Also relevant: https://github.com/blacklanternsecurity/bbot/issues/491

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/2105.
