### ISSUE TITLE
Filedownload Error

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#2102]
![image](https://github.com/user-attachments/assets/0f0fa3bb-89a8-4725-b275-bc8c8c1a884a)

**Comment by TheTechromancer** [comment]
Thanks for reporting. By chance do you still have the log from this scan?

**Comment by TheTechromancer** [comment]
This is a really strange bug, because `filedownload` doesn't consume or produce `DNS_NAMEs`. So how did they get there? Interested to see how this one is reproduced.

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/2107.
