### ISSUE TITLE
Please provide more usage examples for websocket/http/etc outputs. 

### ISSUE THREAD

**Issue by sm00v** [blacklanternsecurity/bbot#221]
Maybe adding more examples to the readme of both CLI usage with different output(saving) options. I ended up just adding a udp send function to the json module because your websocket implementation does not work with a vanilla node/python websocket listener. 

Also, it would be amazing if we could see more usage examples when importing bbot as a lib. For example how to save events out to json using the built in modules rather than creating my own .write(). 

The main thing i'm trying to figure out is how to output the events in a manner that can be captured in real time then saved to an html page. I've written my own parser for the output.json files which will save to an html page but i'd like to append in real time rather than waiting for the entire scan to complete. Also, how can I pass the name of the scan or the -port to a custom listener so that I can keep track of the scan target? I figured if I can change the -port for each unique scan, I could just create a listener on that unique port to track who i'm scanning.

Sorry for the scatter brain lol. I've been tinkering with this for a few weeks.

Overall, beautiful job on this project. The scale of it is pretty impressive. I will be integrating this into my workflow every single pentest. How can I buy you a coffee?

**Comment by sm00v** [comment]
Added a couple lines to bbot/core/event/base.py starting at line 392. Solved my issue of tracking my scan name. I'm sure you've done something intuitive for this already but I can't seem to figure out what it is.
```try: 
            scan_name = self.scan.name
            j["name"] = scan_name
        except Exception as e:
            print('[-] Could not set scan name')
```

**Comment by TheTechromancer** [comment]
Thanks and great questions! 

Each event (`event.json()`) has a `scan` attribute that is the ID of the scan, which looks like this: `SCAN:1dfdae770c69ce510933d7f7c8fe5ee4db50399c`. This is the recommended way to track event <-> scan relationships.

Note that the first event emitted in every scan is the scan event itself:
```json
{
  "type": "SCAN",
  "id": "SCAN:1dfdae770c69ce510933d7f7c8fe5ee4db50399c", <-----------
  "data": "eldritch_cody (SCAN:1dfdae770c69ce510933d7f7c8fe5ee4db50399c)",
  "scope_distance": 0,
  "scan": "SCAN:1dfdae770c69ce510933d7f7c8fe5ee4db50399c",
  "timestamp": 1671657415.317672,
  "source": "SCAN:1dfdae770c69ce510933d7f7c8fe5ee4db50399c",
  "tags": [
    "distance-0"
  ],
  "module": "TARGET"
}
```

The `http` output module has options, which you can specify in `~/.config/bbot/bbot.yml` like so:
```yaml
output_modules:
  http:
    url: http://127.0.0.1:8000
```

... or on the command line:
```bash
bbot ... -om human http -c output_modules.http.url=http://127.0.0.1:8000
```

**Comment by sm00v** [comment]
What exactly does the http output module do? Also, I'm very interested in the agent configuration. Can you describe more of this functionality and in what scenario it might be used?

**Comment by TheTechromancer** [comment]
The http module will make an HTTP request for each event. Each request contains the event's data in JSON. By default it's a POST request but you can change the HTTP method as well via the options.

As for the agent feature, it's internal and currently not in use. We do have plans to flesh it out but right now it's not production-ready.

I've pushed a fix to the websockets module: https://github.com/blacklanternsecurity/bbot/pull/226. I tested it with websocat and it is working now:
```bash
websocat -v -s 1234
bbot ... -om websocket -c output_modules.websocket.url=ws://127.0.0.1:1234
```

**Comment by TheTechromancer** [comment]
@sm00v did this answer your question?

**Comment by TheTechromancer** [comment]
Closing. Feel free to re-open if needed.
