### ISSUE TITLE
9

### ISSUE THREAD

**Issue by sasholy** [blacklanternsecurity/bbot#228]

**Comment by TheTechromancer** [comment]
What are the contents of `/home/kali/.local/lib/python3.10/site-packages/bbot/defaults.yml`?

**Comment by sasholy** [comment]
> 

### BASIC OPTIONS ###

# BBOT working directory
home: ~/.bbot
# Don't output events that are further than this from the main scope
scope_report_distance: 1
# Generate new DNS_NAME and IP_ADDRESS events through DNS resolution
dns_resolution: true
# Limit the number of BBOT threads
max_threads: 25
# Limit the number of DNS threads
max_dns_threads: 100


### ADVANCED OPTIONS ###

# How far out from the main scope to search
scope_search_distance: 1
# How far out from the main scope to resolve DNS names / IPs
scope_dns_search_distance: 2
# Limit how many DNS records can be followed in a row (for malicious/misconfigured DNS records)
dns_resolve_distance: 5

# Infer certain events from others, e.g. IPs from IP ranges, DNS_NAMEs from URLs, etc.
speculate: True
# Passively search event data for URLs, hostnames, emails, etc.
excavate: True
# Summarize activity at the end of a scan
aggregate: True

# HTTP proxy
http_proxy: 
# HTTP timeout (for Python requests; API calls, etc.)
http_timeout: 30
# HTTP timeout (for httpx)
httpx_timeout: 5
# HTTP retries (for httpx)
httpx_retries: 1
# Enable/disable debug messages for web requests/responses
http_debug: false
# Maximum number of HTTP redirects to follow
http_max_redirects: 5
# Set the maximum number of HTTP links that can be followed in a row (0 == no spidering allowed)
web_spider_distance: 0
# Set the maximum directory depth for the web spider
web_spider_depth: 1
# DNS query timeout
dns_timeout: 5
# How many times to retry DNS queries
dns_retries: 1
# Disable BBOT's smart DNS wildcard handling for select domains
dns_wildcard_ignore: []
# How many sanity checks to make when verifying wildcard DNS
# Increase this value if BBOT's wildcard detection isn't working
dns_wildcard_tests: 5
# Skip DNS requests for a certain domain and rdtype after encountering this many timeouts or SERVFAILs
# This helps prevent faulty DNS servers from hanging up the scan
dns_abort_threshold: 10
# Enable/disable filtering of PTR records containing IP addresses
dns_filter_ptrs: true
# Enable/disable debug messages for dns queries
dns_debug: false
# Whether to verify SSL certificates
ssl_verify: false
# How many scan results to keep before cleaning up the older ones
keep_scans: 20
# Web user-agent
user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.79 Safari/537.36
# Completely ignore URLs with these extensions
url_extension_blacklist:
    # images
    - png
    - jpg
    - bmp
    - ico
    - jpeg
    - gif
    - svg
    # web/fonts
    - css
    - woff
    - woff2
    - ttf
    # audio
    - mp3
    - m4a
    - wav
    - flac
    # video
    - mp4
    - mkv
    - avi
    - wmv
    - mov
    - flv
    - webm
# Distribute URLs with these extensions only to httpx (these are omitted from output)
url_extension_httpx_only:
    - js
# Don't output these types of events (they are still distributed to modules)
omit_event_types:
    - HTTP_RESPONSE
    - URL_UNVERIFIED
# URL of BBOT server
agent_url: ''
# Agent Bearer authentication token
agent_token: ''

# Custom interactsh server settings
interactsh_server: null
interactsh_token: null
interactsh_disable: false

**Comment by TheTechromancer** [comment]
Okay it seems to be an issue with one of your python packages. I would start by updating your os:
```bash
apt update; apt upgrade
```
Then uninstall bbot and install it again in a virtualenv:
```bash
python3 -m pip uninstall bbot
# install pipx
python3 -m pip install --user pipx
# add pipx to your path
python3 -m pipx ensurepath
# reboot
reboot
# install bbot
python3 -m pipx install bbot
# run bbot
bbot --help
```

EDIT: @sasholy for the sanity of those reading this would you please edit your above post to use code blocks like so:
~~~
```
<code>
```
~~~
Thanks

**Comment by TheTechromancer** [comment]
@sasholy Did this solve your problem?

**Comment by sasholy** [comment]
> @sasholy Did this solve your problem?

┌──(kali㉿kali)-[~]
└─$ python3 -m pipx install bbot
Error: name 'cmd' is not defined

'/usr/bin/python3 -m venv --clear /home/kali/.local/pipx/shared' failed

I'm just dumb, sorry

**Comment by TheTechromancer** [comment]
It looks like your Python environment is corrupted. You may have multiple versions conflicting, I'm not sure. But I don't think this is a BBOT issue. I would recommend you run BBOT from docker instead:
```bash
docker run blacklanternsecurity/bbot
```

**Comment by sasholy** [comment]
> Похоже, ваша среда Python повреждена. У вас может быть несколько конфликтующих версий, я не уверен. Но я не думаю, что это проблема BBOT. Вместо этого я бы порекомендовал вам запустить BBOT из докера:
> 
> ```shell
> docker run blacklanternsecurity/bbot
> ```

```
┌──(kali㉿kali)-[~]
└─$ docker run blacklanternsecurity/bbot
Unable to find image 'blacklanternsecurity/bbot:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:50588->[::1]:53: read: connection refused.
See 'docker run --help'.
```

**Comment by TheTechromancer** [comment]
It looks like your docker service can't access the internet. I'm sorry but this is beyond the scope of BBOT, so I'm going to close this issue. Feel free to re-open once you get docker working.

**Comment by sasholy** [comment]
To fix, I just did:
pip install --upgrade PyYaml
thx.
