### ISSUE TITLE
Looking to contribute

### ISSUE THREAD

**Issue by prbhtkumr** [blacklanternsecurity/bbot#23]
Hey, I'm looking to contribute to this project. 
Can you please help me get started on the bugs or features I could work on, and point me to discord/slack where I could interact with and ask questions to other contributors?

**Comment by TheTechromancer** [comment]
Hey! Thanks for your interest. You can join the [Black Lantern Security Discord](https://discord.gg/EypB3DgD) to talk about BBOT etc.

Right now what BBOT needs most is modules. If you have an idea for a module, or a module from another tool you want to see in BBOT, this is the best way to contribute.

The best place to start is the [Devving on BBOT](https://github.com/blacklanternsecurity/bbot/wiki#devving-on-bbot) section of the Wiki, which explains how to get started writing modules.
