### ISSUE TITLE
"Reading targets from file" message bug

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#243]
![loadbug](https://user-images.githubusercontent.com/24899338/214759178-8d681918-82a2-4f55-bc05-e2e94b948d33.PNG)

When loading targets from multiple files, the names of the loaded files remain whatever the first file loaded was.

It appears the correct file is actually loaded, and that it is just a glitch with the message.

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/244
