### ISSUE TITLE
‘pipx install bbot’ and ‘pip install bbot’ failed. Help

### ISSUE THREAD

**Issue by huaiyi255** [blacklanternsecurity/bbot#25]
Environment: win10，python3.9

pip install bbot

![image](https://user-images.githubusercontent.com/52989379/188397488-fd1d274a-5b1e-4f4b-9714-ecf869cbd3a5.png)

![image](https://user-images.githubusercontent.com/52989379/188397388-739f4ebf-aeb4-4836-b97b-1bf5ccf9e192.png)

pipx install bbot

![image](https://user-images.githubusercontent.com/52989379/188397785-bb929f54-2ca3-4dd7-990e-e3ddfdbeb518.png)

**Comment by TheTechromancer** [comment]
BBOT does not support Windows. However it should work in WSL.

**Comment by huaiyi255** [comment]
> BBOT 不支持 Windows。但是它应该在 WSL 中工作。

ok，thank
