### ISSUE TITLE
API from secrets.yml not being loaded/used while running the command

### ISSUE THREAD

**Issue by ipk1** [blacklanternsecurity/bbot#270]
Hi,
Amazing tool!!!

i have run in to aproblem where I have configured the API keys in secrets.yml and run the command the tool doesn't pick up the API's, configured all the API's in the default secrets.yml file 
running on MAC OS 13.2
python version 3.9.10

command used 
sudo bbot -f subdomain-enum email-enum cloud-enum web-basic -m naabu gowitness nuclei --allow-deadly -t domain.com -o results --ignore-failed-deps --config secrets.yml

and 
sudo bbot -f subdomain-enum email-enum cloud-enum web-basic -m naabu gowitness nuclei --allow-deadly -t domain.com -o results --ignore-failed-deps --config ~/.config/bbot/secrets.yml

Tool Output:
WARN] bbot.scanner: Setup soft-failed for bevigil: No API key set
[WARN] bbot.scanner: Setup soft-failed for binaryedge: No API key set
[WARN] bbot.scanner: Setup soft-failed for builtwith: No API key set
[WARN] bbot.scanner: Setup soft-failed for c99: No API key set
[WARN] bbot.scanner: Setup soft-failed for censys: No API key set
[WARN] bbot.scanner: Setup soft-failed for fullhunt: No API key set
[WARN] bbot.scanner: Setup soft-failed for github: No API key set
[WARN] bbot.scanner: Setup soft-failed for hunterio: No API key set
[WARN] bbot.scanner: Setup soft-failed for passivetotal: No API key set
[WARN] bbot.scanner: Setup soft-failed for securitytrails: No API key set
[WARN] bbot.scanner: Setup soft-failed for shodan_dns: No API key set
[WARN] bbot.scanner: Setup soft-failed for virustotal: No API key set
[WARN] bbot.scanner: Setup soft-failed for zoomeye: No API key set
![bbot](https://user-images.githubusercontent.com/32953048/216557760-0a7d64e8-4edb-4984-b0ba-10ee6037a8b6.jpg)

**Comment by TheTechromancer** [comment]
The lines are commented out, you need to remove the `#` at the beginning. ;) Also I should note that macos isn't supported right now. We are working on it but currently modules with binaries such as httpx, gowitness, nuclei etc won't work except on Linux.

**Comment by ipk1** [comment]
Hi thanks, how dumb of me ... damn
