### ISSUE TITLE
Module todo: secrets-patterns-db

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#279]
- https://github.com/praetorian-inc/noseyparker
- https://github.com/trufflesecurity/trufflehog
- https://github.com/SnaffCon/Snaffler
- https://github.com/mazen160/secrets-patterns-db

**Comment by TheTechromancer** [comment]
+1 for secrets-patterns-db.

**Comment by TheTechromancer** [comment]
Regexes are effective but there are a lot of false positives. Opened an issue at the main repo:
https://github.com/mazen160/secrets-patterns-db/issues/3.

@liquidsec @aconite33

**Comment by sasholy** [comment]
> * https://github.com/praetorian-inc/noseyparker
> * https://github.com/trufflesecurity/trufflehog
> * https://github.com/SnaffCon/Snaffler
> * https://github.com/mazen160/secrets-patterns-db

How to make templates without duplicates
Or are there no duplicates?
thx.

**Comment by TheTechromancer** [comment]
This is completed
