### ISSUE TITLE
All modules being loaded when not required

### ISSUE THREAD

**Issue by iv1r4x** [blacklanternsecurity/bbot#282]
Description:-
Bbot is loading all modules even though I have been trying to only load httpx.

Expected behavior:-
Ony subdomains should be enumerated.

Command:-
 bbot --flags subdomain-enum --modules httpx --target example.com

Platform info:-
OS: Arch Linux, Installation method: pip, BBOT version: v1.0.4.922

Screenshot:-
![image](https://user-images.githubusercontent.com/48623823/217537876-6fa2a20c-dc1b-45ae-bce4-8c66760cb950.png)

**Comment by TheTechromancer** [comment]
You have enabled the `subdomain-enum` flag which includes a large number of modules. To see a list of all modules and their flags, you can do:
```bash
bbot -l
```
