### ISSUE TITLE
module request: expiration tracking: domains & certificates

### ISSUE THREAD

**Issue by SpamFaux** [blacklanternsecurity/bbot#291]
**Description**
Which feature would you like to see added to BBOT? What are its use cases?

As BBOT already collects some data from Certificates it would be useful to track the certificates themselves for monitoring Valid Through dates. 

Additionally, being able to note if domains are soon to expired - this can highlight potential issues / risks to availability of a target's domain/subdomains.

**Comment by aconite33** [comment]
Domain will be manually
Certificates are doable
When raised as event, compare expiration with current time
Annotate tag with expiring in X days
Domain will have to be registrar, future work would require additional service to review whois data
