### ISSUE TITLE
CIDR list

### ISSUE THREAD

**Issue by ipk1** [blacklanternsecurity/bbot#302]
Hi, is there any option to load a list of CIDRs to be reverse DNSed? and also is there a way to load a list of targets to get subdomains?

regards
ipk1

**Comment by liquidsec** [comment]
If you specify a valid file with -t, like `-t mylist.txt` it will load a list like you are asking. This can include IPs with CIDR notation that will be automatically identified. As long as you haven't explicitly turned off the speculate internal module, those CIDRs will be re-emitted as individual IP addresses automatically.

**Comment by ipk1** [comment]
Hi, Thanks a lot will try

regards
ipk1
