### ISSUE TITLE
"Too many open files" Error with vhost Module

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#32]
This error has been encountered when cancelling a scan with the vhost module enabled.

~~~
[ERRR] bbot.core.helpers.command: Error in _feed_pipe(): [Errno 24] Too many open files: '/root/.bbot/temp/v8gh2nm1k1bok0hnmwdk
~~~

**Comment by liquidsec** [comment]
Having trouble replicating this. Is it possible it was accidentally fixed with the control+c handling changes?

**Comment by liquidsec** [comment]
unable to reproduce, and since this module has change dramatically (along with everything else) since then, it's possible it was already fixed. Closing until we see it again.
