### ISSUE TITLE
Requests Helper should not maintain one session

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#324]
The requests helper currently makes one session for the entire scan. This causes false positives in situations where sending a request again (now with any cookies that may have been assigned) changes the result in unexpected ways. 

Modules that need to operate on a running session should create one themselves and override the session kwarg when calling the helper

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/321
