### ISSUE TITLE
Add command line config validation

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#342]
If a command is provided with -c on the cli, which does not match an existing setting cli should throw an error and exit. The main reason for this is to prevent someone from running a scan with an important option (lets say, disabling interactsh because they are not allowed to run it) and having a typo and thus having the scan behave differently than expected.

**Comment by aconite33** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/451
