### ISSUE TITLE
hackertarget fails to backoff after API limits exceeded

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#483]
At a certain point, hackertarget will begin to deliver API count exceeded messages. When this happens, the expected behavior is that the scan would exclude hackertarget from that point forward, but instead it continues to attempt  at access the hackertarget API and these messages are received:

INFO] bbot.modules.hackertarget: Error retrieving results for youtube.com: Validation failed for ('API count exceeded - Increase Quota with Membership',), {}: Invalid hostname: "api count exceeded - increase quota with membership"

**Comment by TheTechromancer** [comment]
Fixed in bb4802d8ebe0a0cae3c5c9fa473912ffea90ea14
