### ISSUE TITLE
help me output

### ISSUE THREAD

**Issue by MissisEliot** [blacklanternsecurity/bbot#509]
Hello guys
I just want to say - thank you very much for your product

But I'm asking for your help 

right now I'm getting a conclusion 
[SCAN] overzealous_michael (SCAN:d9a6c7a506ea1a6701f0927c35f74a6017e6fbf0) TARGET (distance-0)
[DNS_NAME] xxxx.com TARGET (a-record, cname-record, distance-0, domain, in-scope, mx-record, ns-record, resolved, soa-record, target, txt-record)
[DNS_NAME] xxxx.com sslcert (affiliate, distance-1, resolved, subdomain, txt-record)
[DNS_NAME] xxxx.com sslcert (affiliate, distance-1, resolved, subdomain, txt-record)
[DNS_NAME] xxxx.com sslcert (affiliate, distance-1, domain, ns-record, resolved, soa-record, txt-record)
[DNS_NAME] xxxx.com sslcert (a-record, affiliate, cname-record, distance-1, domain, ns-record, resolved, soa-record)
[DNS_NAME] xxxx.com sslcert (a-record, aaaa-record, affiliate, distance-1, resolved, subdomain)
[DNS_NAME] xxxx.com sslcert (affiliate, distance-1, domain, ns-record, resolved, soa-record)
[DNS_NAME] xxxx.com sslcert (a-record, affiliate, cname-record, distance-1, resolved, subdomain)
[DNS_NAME] xxxx.com sslcert (affiliate, distance-1, domain, ns-record, resolved, soa-record)
[DNS_NAME] xxxx.com sslcert (a-record, affiliate, distance-1, domain, ns-record, resolved, soa-record, txt-record)
[DNS_NAME] xxxx.com sslcert (a-record, affiliate, cname-record, distance-1, resolved, subdomain)

Is there any way to remove redundant information in the form : [DNS_NAME]  sslcert (a-record, affiliate, cname-record, distance-1, resolved, subdomain) 

And to leave only a name of subdomains the list? 
xxxxx.com
qq.xxxx.com
zz.xxxx.com
qww.xxxx.com 

thx

**Comment by aroly** [comment]
Hi,

Not from the team, but you could just filter the output:

`awk '{print $2}' output.txt | sort -u `

should to the trick. 

A.

**Comment by BlaiseOfGlory** [comment]
I'm kind of a excel scrub, so I will often convert the output to a csv and work with it in excel / libre calc. Then filters make it pretty easy to remove redundant data.

**Comment by MissisEliot** [comment]
Dear developers
please add a command so that the output is immediately only subdomains

**Comment by aroly** [comment]
> I'm kind of a excel scrub, so I will often convert the output to a csv and work with it in excel / libre calc. Then filters make it pretty easy to remove redundant data.

Yeah it's another option. 

I like to use cli tool to do everything in one single command line :)

**Comment by TheTechromancer** [comment]
Thanks for your question. I agree it would be nice to have this kind of output.

The reason we haven't implemented this is because we don't like to assume what your criteria is for subdomains. Do you care about unresolved ones? Ones without A records? In-scope subdomains or affiliates? 

Instead of making these decisions for you, we output in a greppable format (in addition to JSON and CSV) so you can easily grab the ones you want.

Here is my personal one-liner for pulling out in-scope, resolved subdomains, which is similar to what you'd get with a tool like Amass:

```bash
grep -F '[DNS_NAME]' output.txt | grep in-scope | cut -f2 | sort -u
```

**Comment by TheTechromancer** [comment]
Closing. Please feel free to comment/reopen if you have more questions.

**Comment by MissisEliot** [comment]
> Закрытие. Пожалуйста, не стесняйтесь комментировать/переоткрывать, если у вас есть дополнительные вопросы.

support thanks for the answer
I understand that the conclusion is sometimes needed varied
But sometimes it would be very convenient if it output as subfiner or amass
just domains. and all .
If possible, add a flag with the output of only domains

Thank you

**Comment by TheTechromancer** [comment]
@MissisEliot we have added a feature that produces a `subdomains.txt` when you run `subdomain-enum`. This file contains only resolved, in-scope subdomains.

I know it's been a while since you opened this issue but I thought you might be interested.

Thanks
