### ISSUE TITLE
Paramminer sometimes takes a long time

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#512]
In cases where BBOT is rate-limited (by a WAF etc) or where a website goes down during the course of the scan, the paramminer modules will run for a *very* long time. We should try and abort the handle_event() if there are too many failed requests in a row.

**Comment by liquidsec** [comment]
Increased error handling, decreased abort threshold, and addressed various inefficiencies  during recent refactor. This should alleviate some of the issues. Aborting on timeout is already occurring.
