### ISSUE TITLE
Asyncify BBOT

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#519]
Asyncifying BBOT would simultaneously solve all the threading/locking issues and significantly improve performance.

**Comment by TheTechromancer** [comment]
Dev happening here: https://github.com/blacklanternsecurity/bbot/tree/async-testing

**Comment by TheTechromancer** [comment]
Side quest: https://github.com/blacklanternsecurity/bbot/issues/530

**Comment by TheTechromancer** [comment]
@SpamFaux the `async-testing` branch is ready for testing.

**Comment by aconite33** [comment]
Pull request tracking: https://github.com/blacklanternsecurity/bbot/pull/539

**Comment by SpamFaux** [comment]
Ready to merge to dev pending PR review.

**Comment by aconite33** [comment]
Closed, MR complete : https://github.com/blacklanternsecurity/bbot/pull/539
