### ISSUE TITLE
Write dedicated (async) test for *every* module

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#530]

**Comment by TheTechromancer** [comment]
@liquidsec your help would be much appreciated with:
- generic_ssrf
- host_header
- smuggler

**Comment by TheTechromancer** [comment]
![image](https://github.com/blacklanternsecurity/bbot/assets/20261699/a01e1100-c0bb-4a4e-a635-6f4c712b76fc)
:D:D:D

**Comment by liquidsec** [comment]
should be complete as of  https://github.com/blacklanternsecurity/bbot/pull/556
