### ISSUE TITLE
Documentation Overhaul

### ISSUE THREAD

**Issue by SpamFaux** [blacklanternsecurity/bbot#563]
Review options for improving BBOT documentation and taking it to the next level. 
- identify areas that documentation is lacking
- improve readability / consumption of documentation
- make it look purty

**Comment by TheTechromancer** [comment]
Documentation frameworks to consider:

- Docusaurus: https://github.com/facebook/docusaurus
- Read the Docs: https://readthedocs.org/
- MkDocs + GitHub Pages
- GitBook

EDIT: mkdocs-material + github pages == winner
![image](https://github.com/blacklanternsecurity/bbot/assets/20261699/9e063270-c922-4b52-a6d5-feafee93651c)

**Comment by TheTechromancer** [comment]
Consider adding a small ToC to the readme:
![image](https://github.com/blacklanternsecurity/bbot/assets/20261699/3f06afad-0569-4593-94e3-ee5634030244)

**Comment by TheTechromancer** [comment]
Dev happening here: https://github.com/blacklanternsecurity/bbot/tree/material-docs.

**Comment by TheTechromancer** [comment]
@SpamFaux would you be open to putting some of your 🔥 Cypher queries into the [Neo4j section](https://github.com/blacklanternsecurity/bbot/blob/material-docs/docs/scanning/output.md#neo4j)?

**Comment by TheTechromancer** [comment]
Documentation is written and merged.

There are two things that would still be nice to add:

- @SpamFaux's Neo4j queries
- @liquidsec explanation of Nuclei module options

**Comment by TheTechromancer** [comment]
@liquidsec has kindly added Nuclei documentation, so I am closing this issue and creating a new one specifically for @SpamFaux Neo4j queries: https://github.com/blacklanternsecurity/bbot/issues/708.
