### ISSUE TITLE
Skip bruteforcing wildcard domains in Dev and Stable

### ISSUE THREAD

**Issue by qf0** [blacklanternsecurity/bbot#566]
**Description**
Which feature would you like to see added to BBOT? What are its use cases?
Reduce time for subdomain enum and massdns to complete by skipping wildcard domains.

**Comment by TheTechromancer** [comment]
Thanks for the suggestion. This has been added in `async-testing` and should be merged into dev soon.

**Comment by TheTechromancer** [comment]
This is now merged into dev.
