### ISSUE TITLE
Typo in ntlm.py will result in two endpoints being sent as one.

### ISSUE THREAD

**Issue by amspartacus1** [blacklanternsecurity/bbot#600]
https://github.com/blacklanternsecurity/bbot/blob/1e10292eb601cb1c2967bd073cc5dc9bb156d680/bbot/modules/ntlm.py#L7C1-L10

This appears to be a typo where _ecp/_ endpoint was backed up to the line before it. Should likely read:

    "",
    "autodiscover/autodiscover.xml",
    "ecp/",
    "ews/",
    "ews/exchange.asmx",

**Comment by TheTechromancer** [comment]
Thanks, good catch. This is already fixed in dev:

https://github.com/blacklanternsecurity/bbot/blob/dev/bbot/modules/ntlm.py#L4-L9
