### ISSUE TITLE
All modules cancel and give traceback exception after scan finishes

### ISSUE THREAD

**Issue by qf0** [blacklanternsecurity/bbot#666]
**Describe the bug**
I ran a scan, and it finished, but the debug logs show the modules canceled and gave traceback errors. A new log file in .bbot/logs wasn't created after the scan finished leading me to believe the scan didn't finish, or there's a bug with the logging system too,

**Expected behavior**
Scan finish with no traceback/cancel exceptions (except no API key, and other normal excepted behavior)

**BBOT Command**
Example: `bbot -t targets.txt `
'bbot -t targets.txt -y -f subdomain-enum,email-enum,web-basic,cloud-enum -m wafw00f,httpx,nmap,wappalyzer,badsecrets,nuclei --allow-deadly -c modules.massdns.max_resolvers=5000 modules.nuclei.mode=technology modules.nuclei.etags=intrusive -om neo4j,human -o /redacted/folder'

**OS, BBOT Installation Method + Version**
Example: `OS: Arch Linux, Installation method: pip, BBOT version: 1.0.3.545`
Note: You can get the bbot version with `bbot --version`
Note: Windows is **not** supported. We have successfully used BBOT on Docker Desktop in the past, however Windows is highly problematic so if you choose this path you are on your own.
'OS: Ubuntu, Installation method: git clone, git switch defcon-release, BBOT version: 0.0.0 (latest defcon-release branch as of 1 week ago). Ubuntu version: 23.04'

**BBOT Config**
Attach your BBOT config (`bbot --current-config`).

**Logs**
[bbot_config.txt](https://github.com/blacklanternsecurity/bbot/files/12344704/bbot_config.txt)
[bbot_debug_log.txt](https://github.com/blacklanternsecurity/bbot/files/12344754/bbot_debug_log.txt) (redacted example logs)

If possible, produce the bug while `--debug` is enabled, and attach the relevant parts of `~/.bbot/logs/bbot.debug.log`
N/A due to sensitive information.

**Screenshots**

**Comment by TheTechromancer** [comment]
Both issues addressed in https://github.com/blacklanternsecurity/bbot/pull/677

**Comment by TheTechromancer** [comment]
@qf0 each scan now gets its own logfiles (`scan.log` and `debug.log`) in its output directory. As for the cancelled / traceback log messages, they are debug messages intended for developers, and are part of BBOT's expected behavior.
