### ISSUE TITLE
Support IP2Location.io IP Geolocation API in BBot Modules

### ISSUE THREAD

**Issue by ip2location-com** [blacklanternsecurity/bbot#685]
I would like to introduce the IP2Location.io IP geolocation API. It has the following advantages compare to other API providers.

- **Fast** - one of the fastest API in the market using multi-location servers and anycast technology
- **Accurate** - based on IP2Location and IP2Proxy database which is available since 2002
- **Free** - free tier with 30,000 queries monthly available to all users who sign-up online

Please consider [IP2Location.io](https://www.ip2location.io) as one of the database source in WordPress IP Geo Block. Feel free to ping me if you have any questions.

Sample Output of Security Plan (Commercial)
`
{
	"ip":"8.8.8.8",
	"country_code":"US",
	"country_name":"United States of America",
	"region_name":"California",
	"city_name":"Mountain View",
	"latitude":37.405992,
	"longitude":-122.078515,
	"zip_code":"94043",
	"time_zone":"-07:00",
	"asn":"15169",
	"as":"Google LLC",
	"isp":"Google LLC",
	"domain":"google.com",
	"net_speed":"T1",
	"idd_code":"1",
	"area_code":"650",
	"weather_station_code":"USCA0746",
	"weather_station_name":"Mountain View",
	"mcc":"-",
	"mnc":"-",
	"mobile_brand":"-",
	"elevation":32,
	"usage_type":"DCH",
	"address_type":"Anycast",
	"continent":{
		"name":"North America",
		"code":"NA",
		"hemisphere":["north","west"],
		"translation":{
			"lang":"ko",
			"value":"북아메리카"
		}
	},
	"country":{
		"name":"United States of America",
		"alpha3_code":"USA",
		"numeric_code":840,
		"demonym":"Americans",
		"flag":"https://cdn.ip2location.io/assets/img/flags/us.png",
		"capital":"Washington, D.C.",
		"total_area":9826675,
		"population":331002651,
		"currency":{
			"code":"USD",
			"name":"United States Dollar",
			"symbol":"$"
		},
		"language":{
			"code":"EN",
			"name":"English"
		},
		"tld":"us",
		"translation":{
			"lang":"ko",
			"value":"미국"
		}
	},
	"region":{
		"name":"California",
		"code":"US-CA",
		"translation":{
			"lang":"ko",
			"value":"캘리포니아주"
		}
	},
	"city":{
		"name":"Mountain View",
		"translation":{
			"lang":null,
			"value":null
		}
	},
	"time_zone_info":{
		"olson":"America/Los_Angeles",
		"current_time":"2022-04-18T23:41:57-07:00",
		"gmt_offset":-25200,
		"is_dst":true,
		"sunrise":"06:27",
		"sunset":"19:47"
	},
	"geotargeting":{
		"metro":"807"
	},
	"ads_category":"IAB19",
	"ads_category_name":"Technology & Computing",
	"district":"San Diego County",
	"is_proxy":false,
	"proxy":{
		"last_seen":18,
		"proxy_type":"DCH",
		"threat":"-",
		"provider":"-",
		"is_vpn": false,
        "is_tor": false,
        "is_data_center": true,
        "is_public_proxy": false,
        "is_web_proxy": false,
        "is_web_crawler": false,
        "is_residential_proxy": false,
        "is_spammer": false,
        "is_scanner": false,
        "is_botnet": false
	}
}
`

**Comment by TheTechromancer** [comment]
Thanks for the suggestion. I've added this to our to-do list.

It may be a little while before we can get to it. In the meantime if you want to give it a shot yourself you can use the [ipstack module](https://github.com/blacklanternsecurity/bbot/blob/stable/bbot/modules/ipstack.py) as a starting point. It converts `IP_ADDRESS` into `GEOLOCATION`, so the functionality should be pretty similar.

**Comment by TheTechromancer** [comment]
@ip2location thanks for the PR. Module has been merged.
