### ISSUE TITLE
Help me plz 

### ISSUE THREAD

**Issue by MissisEliot** [blacklanternsecurity/bbot#686]
Thanks guys for your tool.

sorry for stupid question
help build a comands to collect subdomains as much as possible

or bbot -t evilcorp.com -f subdomain-enum

Is this enough for the maximum collection of subdomains?
thx

**Comment by TheTechromancer** [comment]
Yes that is enough. It includes all the APIs, SSL certs, and also will visit each webpage.

If you wanted to be really thorough you could also enable the [web spider](https://www.blacklanternsecurity.com/bbot/scanning/tips_and_tricks/#web-spider), but this can take a lot longer to finish and most of the time it's overkill.
