### ISSUE TITLE
Documentation: Neo4j Queries

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#708]
It would be nice to have some of @SpamFaux's awesome Neo4j queries in the BBOT docs.

**Comment by cgomez23** [comment]
I would like to bump this issue. Any update here?

**Comment by TheTechromancer** [comment]
I believe @SpamFaux is very close to finishing this.

**Comment by SpamFaux** [comment]
Actively writing these for documentation. Any requests on what kind of queries would help? @cgomez23

**Comment by cgomez23** [comment]
Nothing particular, I am beginning to set up a home lab for CTI with a neo4j instance as my source of truth. This tool could be a great enricher for the feeds I ingest :)

**Comment by TheTechromancer** [comment]
Added in https://github.com/blacklanternsecurity/bbot/pull/859. Should be live here shortly:

https://www.blacklanternsecurity.com/bbot/scanning/output/#neo4j
