### ISSUE TITLE
Is it possible to only output subdomains in a file without creating a dir?

### ISSUE THREAD

**Issue by rew1nter** [blacklanternsecurity/bbot#796]

**Comment by TheTechromancer** [comment]
This is a commonly requested feature that we will hopefully add soon.

In the meantime, you can grep the output like so:

```bash
bbot -t evilcorp.com -f subdomain-enum | grep -F '[DNS_NAME]' | grep in-scope | cut -f2
```

**Comment by TheTechromancer** [comment]
This feature will be added along with presets: https://github.com/blacklanternsecurity/bbot/issues/802.

**Comment by rew1nter** [comment]
What is the new way of doing this after the update?

**Comment by TheTechromancer** [comment]
The presets feature has not been added yet, so currently you can do this by either grepping the output:

> ```bash
> bbot -t evilcorp.com -f subdomain-enum | grep -F '[DNS_NAME]' | grep in-scope | cut -f2
> ```

Or grabbing it directly from `subdomains.txt`, which you can `tail` if you like. BBOT does create a folder, but you can control its name and where it goes:

```bash
bbot -t evilcorp.com -f subdomain-enum -n scan_name -o .
```

The above command will create a folder called `scan_name` in the current directory.
