### ISSUE TITLE
BBOT Presets

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#802]
### Discussed in https://github.com/blacklanternsecurity/bbot/discussions/704

<div type='discussions-op-text'>

<sup>Originally posted by **TheTechromancer** July 11, 2023</sup>
Presets would be an extension / overhaul of the config system that would allow users to specify targets, flags, modules, and config options in "preset" `.yml` files. This would enable us to make user-friendly presets for individual use-cases like web spidering, ffuf'ing, etc. It would also let users re-run an old scan by loading its preset.</div>

**Comment by aconite33** [comment]
Presets
-------------
Flags
Modules
Configs
CLI
Targets


---------------------

`bbot -p mypreset.yml`

**Comment by aconite33** [comment]
Example yml file

```yml
-targets:
    -evilcorp.com
-description: My Preset
-flags:
    -subdomain.enum
    -!web-spider
-exclude-flags:
    -slow
 ```

**Comment by TheTechromancer** [comment]
Added in https://github.com/blacklanternsecurity/bbot/pull/1058.
