### ISSUE TITLE
Less intrusive Sudo handling

### ISSUE THREAD

**Issue by kerrymilan** [blacklanternsecurity/bbot#86]
As discussed in #40, trying a blank sudo password has the potential to lock out accounts or generate failed login alerts when run in a hardened environment. The testing pipeline should set the `BBOT_SUDO_PASS` environment variable to an empty string to avoid coding this behavior into the tool itself. 

If this behavior is confusing (for example, bbot prompts the user for a Sudo password when their account does not require one to escalate), supplement the prompt with "or press enter for none".

If the tool needs to be able to test for an empty password, consider running a command like the following to check for sudo rights without generating a failed logon:

```
SUDO_ASKPASS=/bin/false /bin/sudo -An /bin/true &> /dev/null
```

**Comment by liquidsec** [comment]
I have also observed this in practice recently, in particular when i've had to stop scans quickly when debugging things

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/97
