### ISSUE TITLE
Discord output module hangs on longer messages

### ISSUE THREAD

**Issue by xorond** [blacklanternsecurity/bbot#861]
**Describe the bug**
What happened?

When running a scan with the discord output module, messages/findings which are longer than 2000 characters cannot be sent.
bbot gets a HTTP 400 response from the Discord API, however it keeps trying to send the same message over and over without stopping.
This causes an infinite loop and the scan never finishes until manually aborted.

See relevant log message (after hitting Enter once to increase log level):
```
[VERB] output.discord: Error sending FINDING("{'host': 'abc.xyz.com', 'description': 'Cryptographic Product identified. Prod...", module=badsecrets, tags={'in-scope', 'distance-0'}): status code 400, response: {"content": ["Must be 2000 or fewer in length."]}, retrying in 1 seconds
[VERB] output.discord: Error sending FINDING("{'host': 'abc.xyz.com', 'description': 'Cryptographic Product identified. Prod...", module=badsecrets, tags={'in-scope', 'distance-0'}): status code 400, response: {"content": ["Must be 2000 or fewer in length."]}, retrying in 1 seconds
[VERB] output.discord: Error sending FINDING("{'host': 'abc.xyz.com', 'description': 'Cryptographic Product identified. Prod...", module=badsecrets, tags={'in-scope', 'distance-0'}): status code 400, response: {"content": ["Must be 2000 or fewer in length."]}, retrying in 1 seconds
```

doing "kill discord" on the scan does not solve the problem. It clears the message queue, however the 1 message which is still "processing" keeps the module running in the infinite loop. We have to hit Ctrl+C to stop the scan.

**Expected behavior**
What was supposed to happen?

After receiving HTTP response 400 multiple times from the Discord API, bbot should maybe skip the message altogether, or alternatively shorten the message to be under <2k characters for Discord. Another option would be to chunk the message into multiple messages while respecting the 2k limit.

**BBOT Command**
Example: `bbot -t $domains -f subdomain-enum web-basic -o bbot-results -om discord -c output_modules.discord.webhook_url=$DISCORD_HOOK`

**OS, BBOT Installation Method + Version**
`OS: Arch Linux, Installation method: pipx, BBOT version: v1.1.3`

**Comment by TheTechromancer** [comment]
Thanks for the report. This should be a pretty easy fix.

About the kill command, we recently updated it so it should now forcefully kill the module in addition to emptying the queues. The change is live in the dev branch but should make its way into stable soon.

**Comment by TheTechromancer** [comment]
Fix has been pushed to https://github.com/blacklanternsecurity/bbot/pull/862.
