### ISSUE TITLE
 'float' object is not callable on SSLCERT module

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#88]
Running the SSL cert module constantly produces these errors:

```
DBUG] bbot.modules.sslcert: Error with SSL handshake on xxx.xxx.xxx.xxx port 80: 'float' object is not callable
```

This does not appear to create any false positives or false negatives but may be introducing a performance impact.

**Comment by TheTechromancer** [comment]
Is the proposed fix to avoid scanning port 80 for SSL?

**Comment by TheTechromancer** [comment]
Addressed in https://github.com/blacklanternsecurity/bbot/pull/266
