### ISSUE TITLE
watched_events doesn't work in output modules

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#92]
Output modules seem to ignore the watched_events value, as well as the filter_event method. To specify a particular set of events, currently it is necessary to explicitly check event.type against self.watched_events like this:

```
def handle_event(self, event):
    if event.type in self.watched_events:
        do_stuff()
```

**Comment by TheTechromancer** [comment]
`watched_events` will work, however by default, output modules use a wildcard `*`. So this check would need to be expanded to include the wildcard like so:

```python
if any(x in self.watched_events for x in (event.type, "*"):
        do_stuff()
```

I have tested `filter_event` and it also seems to work fine. However the scope distance checks don't happen with output modules. If you need the functionality you can re-enable it like so:

An easy way to return filter_event to its default functionality:
```python
    def _scope_distance_check(self, event):
        return BaseModule._scope_distance_check(self, event)
```
