### ISSUE TITLE
Configuration files are ignored

### ISSUE THREAD

**Issue by RR-HS** [blacklanternsecurity/bbot#947]
**Describe the bug**
BBOT ignore the configuration files and does not load any scan module at runtime

**Expected behavior**
According to the documentation, BBOT should load the scan modules specified in the configuration files/the merged file. By looking to the current config (commnad --current-config), BBOT includes all the modules while in the configuration files (bbot.yml, defaults.yml, secrets.yml) we restricted the modules to only two (crt and asn, the other are commented).
Running BBOT the tool does not consider any module shown in the current config files.

**BBOT Commands**
bbot -t google.it
bbot -c bbot.yml -t google.it

**OS, BBOT Installation Method + Version**
OS: Ubuntu, Installation method: poetry, BBOT version: 1.0.3
OS: Kali Linux, Installation method: pipx, BBOT version: 1.1.3
OS: Ubuntu, Installation method: Docker, BBOT version: 1.1.3 

**BBOT Config**
[bbot_current_config.txt](https://github.com/blacklanternsecurity/bbot/files/13785994/bbot_current_config.txt)
[bbot.yml](https://github.com/blacklanternsecurity/bbot/files/13785961/bbot.txt)
[defaults.yml](https://github.com/blacklanternsecurity/bbot/files/13785963/defaults.txt)
[secrets.yml](https://github.com/blacklanternsecurity/bbot/files/13785964/secrets.txt)

**Logs**
[bbot.debug.log](https://github.com/blacklanternsecurity/bbot/files/13785976/bbot.debug.log)

**Comment by TheTechromancer** [comment]
Thanks for the bug report and the detailed description. 

> According to the documentation, BBOT should load the scan modules specified in the configuration files/the merged file.

This is only true for internal modules. Normal scan modules must be specified on the command line via `-m` or `-f`. The config is primarily for setting individual options for those modules, such as API keys.

EDIT: in the future, it will be possible to specify everything via the config file. It is in the roadmap to support this.
